const announcementForm=document.getElementById('announcementForm');
const messageEl=document.getElementById('announcementMessage');
const listEl=document.getElementById('announcementsList');
const typeEl=document.getElementById('announcementType');
const targetTypeEl=document.getElementById('targetType');
const departmentEl=document.getElementById('targetDepartmentId');
const employeeEl=document.getElementById('targetEmployeeId');
const departmentField=document.getElementById('departmentField');
const employeeField=document.getElementById('employeeField');
const statusEl=document.getElementById('announcementStatus');
const selectedBox=document.getElementById('selectedRecipientsBox');
const countText=document.getElementById('announcementsCountText');
let announcements=[];let departments=[];let employees=[];let activeFilter='all';
function msg(text,isError=false){messageEl.textContent=text||'';messageEl.className='inline-message '+(isError?'error-message':'success-message')}
function v(id){return(document.getElementById(id)?.value||'').trim()}
function sv(id,val){let el=document.getElementById(id);if(el)el.value=val??''}
async function api(path,opt={}){let r=await fetch(`${API_BASE_URL}${path}`,{...opt,headers:{Authorization:`Bearer ${token}`,'Content-Type':'application/json',...(opt.headers||{})}});let d=await r.json().catch(()=>({}));if(!r.ok)throw new Error(d.error||'فشل تنفيذ العملية');return d}
function today(){return new Date().toISOString().slice(0,10)}
function statusLabel(s){return s==='draft'?'مسودة':s==='archived'?'مؤرشف':s==='expired'?'منتهي':'منشور'}
function typeLabel(t){return t==='general'?'إعلان عام':'إعلان خاص'}
function fmtDate(x){return x?String(x).slice(0,10):'بدون تاريخ'}
function setBtnLoading(btn,text){btn.disabled=true;btn.dataset.oldText=btn.textContent;btn.textContent=text}
function stopBtnLoading(btn){btn.disabled=false;btn.textContent=btn.dataset.oldText||btn.textContent}
function selectedEmployeeIds(){return Array.from(employeeEl.selectedOptions||[]).map(o=>Number(o.value)).filter(Boolean)}
function targetLabel(a){if(a.target_type==='all')return'جميع موظفي الشركة';if(a.target_type==='employee'){let names=a.target_employee_names||[];if(names.length)return `موظفون محددون: ${names.join('، ')}`;return a.target_employee_name?`الموظف: ${a.target_employee_name}`:'موظفون محددون'}return a.target_department_name?`القسم: ${a.target_department_name}`:'قسم كامل'}
async function init(){let user=await loadLoggedUser();if(!user)return;sv('startDate',today());await Promise.all([loadDepartments(),loadEmployees(),loadAnnouncements()]);updateTargetUI();updateSummary()}
async function loadDepartments(){try{let d=await api('/departments');departments=d.departments||[];departmentEl.innerHTML='<option value="">اختر القسم</option>'+departments.map(dep=>`<option value="${dep.id}">${dep.parent_name?dep.parent_name+' / ':''}${dep.name}</option>`).join('')}catch(e){departmentEl.innerHTML='<option value="">تعذر تحميل الأقسام</option>'}}
async function loadEmployees(){try{let d=await api('/employees?limit=500');employees=d.employees||[]}catch(e){employees=[]}}
async function loadAnnouncements(){listEl.innerHTML='<div class="empty-soft">جاري تحميل الإعلانات...</div>';try{let d=await api('/announcements');announcements=d.announcements||[];renderAnnouncements();updateSummary()}catch(e){listEl.innerHTML=`<div class="empty-soft">${e.message}</div>`}}
function updateSummary(){let now=today();document.getElementById('annTotalCard').textContent=announcements.length;document.getElementById('annGeneralCard').textContent=announcements.filter(a=>a.type==='general').length;document.getElementById('annPrivateCard').textContent=announcements.filter(a=>a.type==='private').length;document.getElementById('annPublishedCard').textContent=announcements.filter(a=>a.status==='published'&&a.is_active&&(!a.end_date||String(a.end_date).slice(0,10)>=now)).length}
function filteredAnnouncements(){let now=today();return announcements.filter(a=>{if(activeFilter==='all')return true;if(activeFilter==='general'||activeFilter==='private')return a.type===activeFilter;if(activeFilter==='published')return a.status==='published'&&a.is_active&&(!a.end_date||String(a.end_date).slice(0,10)>=now);if(activeFilter==='expired')return a.end_date&&String(a.end_date).slice(0,10)<now;if(activeFilter==='archived')return a.status==='archived'||!a.is_active;return true})}
function renderAnnouncements(){let list=filteredAnnouncements();if(countText)countText.textContent=`عرض ${list.length} من أصل ${announcements.length} إعلان`;if(!list.length){listEl.innerHTML='<div class="empty-soft">لا توجد إعلانات حالياً</div>';return}listEl.innerHTML=list.map(a=>`<article class="announcement-card ${a.type==='general'?'general':'private'}"><div class="announcement-card-head"><span class="announcement-badge ${a.type==='general'?'general':'private'}">${typeLabel(a.type)}</span><span class="announcement-status">${statusLabel(a.status)}</span></div><h3>${a.title}</h3><p>${a.content}</p><div class="announcement-meta"><span>الجمهور المستهدف: ${targetLabel(a)}</span><span>عدد المستلمين: ${a.recipients_count??'حسب النطاق'}</span><span>تاريخ النشر: ${fmtDate(a.published_at||a.created_at)}</span><span>تاريخ الانتهاء: ${a.end_date?fmtDate(a.end_date):'غير محدد'}</span></div><footer><strong>نشر بواسطة: ${a.publisher_name||'-'}</strong><small>${a.publisher_job_title||'-'}</small></footer><div class="announcement-actions-row"><button class="secondary-btn small-btn" data-action="edit" data-id="${a.id}">تعديل</button><button class="danger-btn small-btn" data-action="archive" data-id="${a.id}">أرشفة</button></div></article>`).join('')}
function updateTargetUI(){let type=typeEl.value;let previous=targetTypeEl.value;if(type==='general'){targetTypeEl.innerHTML='<option value="all">جميع موظفي الشركة</option><option value="department">موظفو قسم محدد</option>';targetTypeEl.value=previous==='department'?'department':'all'}else{targetTypeEl.innerHTML='<option value="department">قسم كامل</option><option value="employee">موظف/موظفون من قسم</option>';targetTypeEl.value=previous==='employee'?'employee':'department'}let target=targetTypeEl.value;departmentField.style.display=target==='department'||target==='employee'?'grid':'none';employeeField.style.display=target==='employee'?'grid':'none';renderEmployeesByDepartment();updateRecipientsPreview()}
function employeeDepartmentIds(e){let ids=new Set();if(e.department_id)ids.add(String(e.department_id));if(e.primary_department?.department_id)ids.add(String(e.primary_department.department_id));(e.departments||[]).forEach(d=>d.department_id&&ids.add(String(d.department_id)));(e.additional_departments||[]).forEach(d=>d.department_id&&ids.add(String(d.department_id)));return Array.from(ids)}
function renderEmployeesByDepartment(selectedIds=[]){let dep=departmentEl.value;let list=dep?employees.filter(e=>employeeDepartmentIds(e).includes(String(dep))):[];employeeEl.innerHTML=list.length?list.map(e=>`<option value="${e.id}" ${selectedIds.map(String).includes(String(e.id))?'selected':''}>${e.full_name} - ${e.employee_number||e.id}</option>`).join(''):'<option value="" disabled>اختر القسم أولًا أو لا يوجد موظفون</option>';updateRecipientsPreview()}
function updateRecipientsPreview(){let target=targetTypeEl.value;if(!selectedBox)return;if(target==='all'){selectedBox.textContent='سيصل الإعلان إلى جميع موظفي الشركة.';return}if(target==='department'){let dep=departments.find(d=>String(d.id)===String(departmentEl.value));selectedBox.textContent=dep?`سيصل الإعلان إلى كل موظفي قسم: ${dep.name}`:'اختر القسم لتحديد نطاق الإعلان.';return}let names=Array.from(employeeEl.selectedOptions||[]).map(o=>o.textContent.trim()).filter(Boolean);selectedBox.textContent=names.length?`المستلمون المختارون (${names.length}): ${names.join('، ')}`:'اختر القسم ثم اختر موظفًا أو أكثر.'}
function resetForm(){announcementForm.reset();sv('announcementId','');sv('startDate',today());sv('announcementStatus','published');document.getElementById('formTitle').textContent='إنشاء إعلان';msg('');updateTargetUI()}
function validate(){let start=v('startDate'),end=v('endDate'),target=targetTypeEl.value;if(!v('announcementTitle'))return'عنوان الإعلان مطلوب';if(!v('announcementContent'))return'نص الإعلان مطلوب';if(!typeEl.value)return'يرجى اختيار نوع الإعلان';if(!start)return'تاريخ بداية الظهور مطلوب';if(end&&end<start)return'تاريخ النهاية لا يمكن أن يكون قبل تاريخ البداية';if((target==='department'||target==='employee')&&!departmentEl.value)return'يرجى اختيار القسم';if(target==='employee'&&!selectedEmployeeIds().length)return'يرجى اختيار موظف واحد على الأقل';return null}
function payload(statusOverride=null){let ids=selectedEmployeeIds();return{title:v('announcementTitle'),content:v('announcementContent'),type:typeEl.value,target_type:targetTypeEl.value,target_department_id:departmentEl.value?Number(departmentEl.value):null,target_employee_id:ids[0]||null,target_employee_ids:ids,start_date:v('startDate'),end_date:v('endDate')||null,status:statusOverride||statusEl.value}}
async function saveAnnouncement(statusOverride=null,btn=null){let err=validate();if(err){msg(err,true);return}if(btn)setBtnLoading(btn,'يتم الحفظ...');try{let id=v('announcementId');let d=await api(id?`/announcements/${id}`:'/announcements',{method:id?'PUT':'POST',body:JSON.stringify(payload(statusOverride))});msg(d.message||'تم حفظ الإعلان');resetForm();await loadAnnouncements()}catch(e){msg(e.message,true)}finally{if(btn)stopBtnLoading(btn)}}
function editAnnouncement(id){let a=announcements.find(x=>String(x.id)===String(id));if(!a)return;sv('announcementId',a.id);sv('announcementTitle',a.title);sv('announcementContent',a.content);sv('announcementType',a.type);updateTargetUI();sv('targetType',a.target_type);updateTargetUI();sv('targetDepartmentId',a.target_department_id);renderEmployeesByDepartment(a.target_employee_ids?.length?a.target_employee_ids:[a.target_employee_id].filter(Boolean));sv('startDate',fmtDate(a.start_date));sv('endDate',a.end_date?fmtDate(a.end_date):'');sv('announcementStatus',a.status||'published');document.getElementById('formTitle').textContent='تعديل إعلان';updateRecipientsPreview();scrollTo({top:0,behavior:'smooth'})}
async function archiveAnnouncement(id){if(!confirm('هل أنت متأكد من أرشفة هذا الإعلان؟'))return;try{let d=await api(`/announcements/${id}/archive`,{method:'PATCH'});msg(d.message||'تم أرشفة الإعلان');await loadAnnouncements()}catch(e){msg(e.message,true)}}
announcementForm.addEventListener('submit',e=>{e.preventDefault();saveAnnouncement('published',document.getElementById('publishAnnouncementBtn'))});document.getElementById('draftAnnouncementBtn').addEventListener('click',()=>saveAnnouncement('draft',document.getElementById('draftAnnouncementBtn')));document.getElementById('resetAnnouncementBtn').addEventListener('click',resetForm);document.getElementById('cancelEditBtn').addEventListener('click',resetForm);document.getElementById('refreshAnnouncementsBtn').addEventListener('click',loadAnnouncements);typeEl.addEventListener('change',updateTargetUI);targetTypeEl.addEventListener('change',updateTargetUI);departmentEl.addEventListener('change',()=>renderEmployeesByDepartment());employeeEl.addEventListener('change',updateRecipientsPreview);document.querySelectorAll('.announcement-filter').forEach(b=>b.addEventListener('click',()=>{document.querySelectorAll('.announcement-filter').forEach(x=>x.classList.remove('active'));b.classList.add('active');activeFilter=b.dataset.filter;renderAnnouncements()}));listEl.addEventListener('click',e=>{let b=e.target.closest('button');if(!b)return;if(b.dataset.action==='edit')editAnnouncement(b.dataset.id);if(b.dataset.action==='archive')archiveAnnouncement(b.dataset.id)});
init();
