const tableBody=document.getElementById('attendanceTableBody');
const form=document.getElementById('attendanceForm');
const formMessage=document.getElementById('formMessage');
const employeeSelect=document.getElementById('employee_id');
const searchInput=document.getElementById('attendanceSearchInput');
const employeeFilter=document.getElementById('attendanceEmployeeFilter');
const mainDepFilter=document.getElementById('attendanceMainDepartmentFilter');
const subDepFilter=document.getElementById('attendanceSubDepartmentFilter');
const statusFilter=document.getElementById('attendanceStatusFilter');
const monthFilter=document.getElementById('attendanceMonthFilter');
const fromDate=document.getElementById('attendanceFromDate');
const toDate=document.getElementById('attendanceToDate');
const refreshBtn=document.getElementById('refreshAttendanceBtn');
const exportBtn=document.getElementById('exportAttendanceBtn');
const countText=document.getElementById('attendanceCountText');
const lastBox=document.getElementById('lastMovementBox');
const attendanceCards=document.getElementById('attendanceCards');
const cards={total:document.getElementById('totalAttendanceCard'),present:document.getElementById('presentAttendanceCard'),late:document.getElementById('lateAttendanceCard'),absent:document.getElementById('absentAttendanceCard')};
let records=[];let employees=[];
const labels={present:'حاضر',absent:'غائب',late:'متأخر',leave:'إجازة',early_leave:'خروج مبكر'};
const classes={present:'status-active',absent:'status-danger',late:'status-warning',leave:'badge-blue',early_leave:'status-warning'};
function showMessage(t,b){formMessage.textContent=t;formMessage.className='inline-message '+(b?'error-message':'success-message')}
function fmt(d){return d?String(d).split('T')[0]:'-'}
function detail(label,value){return `<div class="detail-item"><span class="detail-label">${label}</span><span class="detail-value">${value||'-'}</span></div>`}
function rowClass(r){if(r.status==='absent'&&r.absence_reason==='excused_leave')return 'absence-excused-row';if(r.status==='absent')return 'absence-unexcused-row';if(r.status==='late')return 'late-row';return ''}
function statusBadgeClass(r){if(r.status==='absent'&&r.absence_reason==='excused_leave')return 'badge-blue';if(r.status==='absent')return 'status-danger';return classes[r.status]||'badge-blue'}
function statusText(r){if(r.status==='absent'&&r.absence_reason==='excused_leave')return 'غائب بعذر';if(r.status==='absent')return 'غائب بدون عذر';return labels[r.status]||r.status}
async function initAttendance(){let u=await loadLoggedUser();if(!u||u.role==='employee'){location.href='./dashboard.html';return}document.getElementById('attendance_date').value=new Date().toISOString().split('T')[0];await loadEmployees();await loadAttendance()}
async function loadEmployees(){let r=await fetch(`${API_BASE_URL}/employees`,{headers:{Authorization:`Bearer ${token}`}});let d=await r.json();if(!r.ok)return;employees=d.employees||[];employeeSelect.innerHTML='<option value="">اختر الموظف</option>';employeeFilter.innerHTML='<option value="">كل الموظفين</option>';employees.forEach(e=>{let label=`${e.full_name} - ${e.primary_department?.department_name||e.department_name||'بدون قسم'}`;employeeSelect.innerHTML+=`<option value="${e.id}">${label}</option>`;employeeFilter.innerHTML+=`<option value="${e.id}">${label}</option>`});renderDepartmentFilters()}
function renderDepartmentFilters(){let main=new Map(),sub=new Map();employees.forEach(e=>{if(e.primary_department)main.set(String(e.primary_department.department_id),e.primary_department.department_name);(e.additional_departments||[]).forEach(x=>sub.set(String(x.department_id),x.department_name))});mainDepFilter.innerHTML='<option value="">كل الأقسام الرئيسية</option>'+Array.from(main).map(([id,name])=>`<option value="${id}">${name}</option>`).join('');subDepFilter.innerHTML='<option value="">كل الأقسام الفرعية</option>'+Array.from(sub).map(([id,name])=>`<option value="${id}">${name}</option>`).join('')}
async function loadAttendance(){countText.textContent='جاري تحميل البيانات...';let r=await fetch(`${API_BASE_URL}/attendance`,{headers:{Authorization:`Bearer ${token}`}});let d=await r.json();if(!r.ok){tableBody.innerHTML=`<tr><td colspan="11">${d.error||'تعذر تحميل البيانات'}</td></tr>`;if(attendanceCards)attendanceCards.innerHTML='<div class="empty-list">تعذر تحميل البيانات</div>';countText.textContent='تعذر تحميل البيانات';return}records=d.attendance||[];renderAttendance()}
function filtered(){let q=searchInput.value.trim().toLowerCase(),emp=employeeFilter.value,main=mainDepFilter.value,sub=subDepFilter.value,st=statusFilter.value,month=monthFilter.value,from=fromDate.value,to=toDate.value;return records.filter(r=>{let date=fmt(r.attendance_date);let text=[r.employee_name,r.notes,r.status,r.absence_reason,r.primary_department_name,r.sub_department_name].filter(Boolean).join(' ').toLowerCase();return(!q||text.includes(q))&&(!emp||String(r.employee_id)===emp)&&(!main||String(r.primary_department_id)===main)&&(!sub||String(r.sub_department_id)===sub)&&(!st||r.status===st)&&(!month||date.startsWith(month))&&(!from||date>=from)&&(!to||date<=to)})}
function renderCards(list){cards.total.textContent=list.length;cards.present.textContent=list.filter(r=>r.status==='present').length;cards.late.textContent=list.filter(r=>r.status==='late').length;cards.absent.textContent=list.filter(r=>r.status==='absent').length}
function renderLastMovement(){let empId=employeeFilter.value||employeeSelect.value;if(!empId){lastBox.innerHTML=[detail('الموظف','اختر موظفًا لعرض آخر حركة'),detail('آخر تاريخ','-'),detail('الدخول','-'),detail('الخروج','-'),detail('الحالة','-'),detail('المصدر','-')].join('');return}let empRecords=records.filter(r=>String(r.employee_id)===String(empId)).sort((a,b)=>String(b.attendance_date).localeCompare(String(a.attendance_date))||b.id-a.id);let r=empRecords[0];if(!r){lastBox.innerHTML=[detail('الموظف','لا توجد حركات لهذا الموظف'),detail('آخر تاريخ','-'),detail('الدخول','-'),detail('الخروج','-'),detail('الحالة','-'),detail('المصدر','-')].join('');return}lastBox.innerHTML=[detail('الموظف',r.employee_name),detail('آخر تاريخ',fmt(r.attendance_date)),detail('الدخول',r.check_in||'-'),detail('الخروج',r.check_out||'-'),detail('الحالة',statusText(r)),detail('المصدر',sourceLabel(r.source))].join('')}
function sourceLabel(s){return{system:'النظام',fingerprint:'البصمة',manual:'إدخال يدوي',approved_leave:'إجازة معتمدة',auto_monitor:'مراقبة تلقائية'}[s]||s||'النظام'}
function renderAttendanceCards(list){if(!attendanceCards)return;if(!list.length){attendanceCards.innerHTML='<div class="empty-list">لا توجد سجلات مطابقة</div>';return}attendanceCards.innerHTML=list.map(r=>`<article class="attendance-card"><div class="attendance-card-head"><div><h3>${r.employee_name||'-'}</h3><p>${r.primary_department_name||'-'} ${r.sub_department_name?`• ${r.sub_department_name}`:''}</p></div><span class="mini-badge ${statusBadgeClass(r)}">${statusText(r)}</span></div><div class="attendance-card-grid">${detail('التاريخ',fmt(r.attendance_date))}${detail('الدخول',r.check_in||'-')}${detail('الخروج',r.check_out||'-')}${detail('المصدر',sourceLabel(r.source))}${detail('ملاحظات',r.notes||'-')}</div><div class="employee-card-actions"><button class="danger-btn small-btn" onclick="deleteAttendance(${r.id})">حذف</button></div></article>`).join('')}
function renderAttendance(){let list=filtered();countText.textContent=`عرض ${list.length} من أصل ${records.length} سجل`;renderCards(list);renderLastMovement();renderAttendanceCards(list);if(!list.length){tableBody.innerHTML='<tr><td colspan="11">لا توجد سجلات مطابقة</td></tr>';return}tableBody.innerHTML='';list.forEach(r=>{let tr=document.createElement('tr');tr.className=rowClass(r);tr.innerHTML=`<td>${r.id}</td><td>${r.employee_name}</td><td>${r.primary_department_name||'-'}</td><td>${r.sub_department_name||'-'}</td><td>${fmt(r.attendance_date)}</td><td>${r.check_in||'-'}</td><td>${r.check_out||'-'}</td><td><span class="status-badge ${statusBadgeClass(r)}">${statusText(r)}</span></td><td>${sourceLabel(r.source)}</td><td>${r.notes||'-'}</td><td><div class="row-actions"><button class="danger-btn small-btn" onclick="deleteAttendance(${r.id})">حذف</button></div></td>`;tableBody.appendChild(tr)})}
form.addEventListener('submit',async e=>{e.preventDefault();let body={employee_id:employeeSelect.value,attendance_date:document.getElementById('attendance_date').value,check_in:document.getElementById('check_in').value||null,check_out:document.getElementById('check_out').value||null,status:document.getElementById('status').value,source:document.getElementById('source').value,notes:document.getElementById('notes').value.trim()};if(!body.employee_id||!body.attendance_date){showMessage('الموظف والتاريخ مطلوبان',true);return}let r=await fetch(`${API_BASE_URL}/attendance`,{method:'POST',headers:{Authorization:`Bearer ${token}`,'Content-Type':'application/json'},body:JSON.stringify(body)});let d=await r.json();if(!r.ok){showMessage(d.error||'تعذر حفظ سجل الحضور',true);return}showMessage(d.message||'تم حفظ سجل الحضور');form.reset();document.getElementById('attendance_date').value=new Date().toISOString().split('T')[0];await loadAttendance()});
async function deleteAttendance(id){if(!confirm('هل أنت متأكد من حذف سجل الحضور؟'))return;let r=await fetch(`${API_BASE_URL}/attendance/${id}`,{method:'DELETE',headers:{Authorization:`Bearer ${token}`}});let d=await r.json();showMessage(d.message||d.error,!r.ok);await loadAttendance()}
function exportCSV(){let rows=[['id','employee','main_department','sub_department','date','check_in','check_out','status','source','notes'],...filtered().map(r=>[r.id,r.employee_name,r.primary_department_name||'',r.sub_department_name||'',fmt(r.attendance_date),r.check_in||'',r.check_out||'',statusText(r),sourceLabel(r.source),r.notes||''])];let csv=rows.map(row=>row.map(v=>`"${String(v??'').replace(/"/g,'""')}"`).join(',')).join('\n');let blob=new Blob(['\uFEFF'+csv],{type:'text/csv;charset=utf-8;'});let url=URL.createObjectURL(blob);let a=document.createElement('a');a.href=url;a.download='attendance.csv';a.click();URL.revokeObjectURL(url)}
[searchInput,employeeFilter,mainDepFilter,subDepFilter,statusFilter,monthFilter,fromDate,toDate].forEach(el=>{el.addEventListener('input',renderAttendance);el.addEventListener('change',renderAttendance)});
employeeSelect.addEventListener('change',renderLastMovement);refreshBtn.addEventListener('click',loadAttendance);exportBtn.addEventListener('click',exportCSV);
initAttendance();
