const epApi=async(path,opt={})=>{const r=await fetch(`${API_BASE_URL}/employee-portal${path}`,{...opt,headers:{Authorization:`Bearer ${token}`,'Content-Type':'application/json',...(opt.headers||{})}});const d=await r.json().catch(()=>({}));if(!r.ok)throw new Error(d.error||'فشل تحميل البيانات');return d};
const el=(id)=>document.getElementById(id);
const fmtDate=(x)=>x?String(x).slice(0,10):'-';
const fmtTime=(x)=>x?String(x).slice(0,8):'-';
const statusLabel=(s)=>({present:'حاضر',late:'متأخر',absent:'غائب',early_leave:'خروج مبكر',leave:'إجازة',pending:'قيد الانتظار',approved:'موافق عليه',rejected:'مرفوض',cancelled:'ملغي',needs_info:'يحتاج معلومات',draft:'مسودة'}[s]||s||'-');
const typeLabel=(s)=>({leave:'طلب إجازة',exit:'طلب مغادرة',advance:'طلب سلفة',complaint:'شكوى',custom:'طلب مخصص',resignation:'طلب استقالة'}[s]||s||'-');
const detail=(label,value)=>`<div class="detail-item"><span class="detail-label">${label}</span><span class="detail-value">${value??'-'}</span></div>`;
const money=(x)=>Number(x||0).toFixed(2);
const isEmployeeOnly=(user)=>{const roles=user.roles||[];const permissions=user.permissions||[];if(roles.includes('admin')||permissions.includes('system.admin'))return false;if(roles.length===1&&roles[0]==='employee')return true;const adminSignals=['.department','.all','manage','finance.dashboard','finance.settings','finance.payroll_slips.create','finance.payroll_slips.approve','finance.advances.manage','attendance.manual','employees.view.department','employees.view.all','departments.','shifts.','permissions.','users.','announcements.create'];return !permissions.some(p=>adminSignals.some(s=>p.includes(s)))};

async function initMyProfile(){const user=await loadLoggedUser();if(!user)return;try{const d=await epApi('/profile');const p=d.profile||{};const shift=d.current_shift||{};el('profilePersonal').innerHTML=[detail('تاريخ الميلاد',fmtDate(p.birth_date||p.date_of_birth)),detail('تاريخ التعيين',fmtDate(p.hire_date)),detail('الجنسية',p.nationality||'-'),detail('الجنس',p.gender||'-')].join('');el('profileLeaves').innerHTML=[detail('الرصيد الحالي',p.leave_balance_current??14),detail('الأيام المستهلكة',p.leave_days_consumed??0),detail('المتبقي حتى اليوم',p.leave_balance_remaining??((p.leave_balance_current??14)-(p.leave_days_consumed??0)))].join('');el('profileWork').innerHTML=[detail('القسم الرئيسي',p.department_name||'-'),detail('القسم الفرعي',(d.sub_departments||[]).map(x=>x.name).join('، ')||'-'),detail('المسمى الوظيفي',p.job_title_label||p.job_title_name||p.job_title||'-'),detail('الشفت الحالي',shift.name||'الدوام الافتراضي')].join('');el('profileContact').innerHTML=[detail('رقم الهاتف',p.phone||'-'),detail('البريد الإلكتروني',p.email||'-')].join('')}catch(e){el('profilePersonal').innerHTML=`<div class="empty-soft">${e.message}</div>`}}

function requestFields(type){if(type==='leave')return `<div class="field-shell"><label class="field-label">نوع الإجازة</label><select id="reqLeaveType"><option value="annual">سنوية</option><option value="sick">مرضية</option><option value="emergency">طارئة</option><option value="unpaid">بدون راتب</option></select></div><div class="field-shell"><label class="field-label">من تاريخ</label><input type="date" id="reqStart"></div><div class="field-shell"><label class="field-label">إلى تاريخ</label><input type="date" id="reqEnd"></div>`;
if(type==='exit')return `<div class="field-shell"><label class="field-label">نوع المغادرة</label><select id="reqExitType"><option value="personal">شخصية</option><option value="work">عمل</option><option value="medical">طبية</option></select></div><div class="field-shell"><label class="field-label">التاريخ</label><input type="date" id="reqExitDate"></div><div class="field-shell"><label class="field-label">وقت المغادرة</label><input type="time" id="reqExitTime"></div><div class="field-shell"><label class="field-label">وقت العودة</label><input type="time" id="reqReturnTime"></div>`;
if(type==='advance')return `<div class="field-shell"><label class="field-label">المبلغ</label><input type="number" id="reqAmount" min="0" step="0.01"></div><div class="field-shell"><label class="field-label">طريقة الخصم</label><select id="reqDeduction"><option value="one_time">مرة واحدة</option><option value="installments">أقساط</option></select></div><div class="field-shell"><label class="field-label">عدد الأقساط</label><input type="number" id="reqInstallments" min="1" value="1"></div><div class="field-shell"><label class="field-label">بداية الخصم</label><input type="month" id="reqStartMonth"></div>`;
if(type==='complaint')return `<div class="field-shell full-width"><label class="field-label">عنوان الشكوى</label><input id="reqTitle"></div>`;
return `<div class="field-shell full-width"><label class="field-label">عنوان الطلب</label><input id="reqTitle"></div>`}
function buildReqData(type){const reason=el('reqReason')?.value||'';const details=el('reqDetails')?.value||'';if(type==='leave')return{leave_type:el('reqLeaveType').value,start_date:el('reqStart').value,end_date:el('reqEnd').value,reason,notes:details};if(type==='exit')return{exit_type:el('reqExitType').value,exit_date:el('reqExitDate').value,exit_time:el('reqExitTime').value,return_time:el('reqReturnTime').value,reason,notes:details};if(type==='advance')return{amount:Number(el('reqAmount').value||0),deduction_method:el('reqDeduction').value,installments_count:Number(el('reqInstallments').value||1),deduction_start_month:el('reqStartMonth').value,reason,notes:details};return{title:el('reqTitle')?.value||typeLabel(type),reason,details,notes:details}}
async function initMyRequests(){const user=await loadLoggedUser();if(!user)return;const type=el('requestType');const box=el('dynamicFields');type.addEventListener('change',()=>{box.innerHTML=requestFields(type.value)});box.innerHTML=requestFields(type.value);await loadMyRequests();el('requestForm').addEventListener('submit',async(e)=>{e.preventDefault();try{const body={request_type:type.value,status:'pending',request_data:buildReqData(type.value)};const r=await fetch(`${API_BASE_URL}/leaves`,{method:'POST',headers:{Authorization:`Bearer ${token}`,'Content-Type':'application/json'},body:JSON.stringify(body)});const d=await r.json().catch(()=>({}));if(!r.ok)throw new Error(d.error||'تعذر إرسال الطلب');el('requestMsg').textContent=d.message||'تم إرسال الطلب';el('requestMsg').className='inline-message success-message';e.target.reset();box.innerHTML=requestFields(type.value);await loadMyRequests()}catch(err){el('requestMsg').textContent=err.message;el('requestMsg').className='inline-message error-message'}})}
async function fetchSelfRequests(){try{const r=await fetch(`${API_BASE_URL}/leaves`,{headers:{Authorization:`Bearer ${token}`}});const d=await r.json().catch(()=>({}));if(r.ok&&Array.isArray(d.requests))return d.requests;if(r.ok&&Array.isArray(d.leaves))return d.leaves.map(x=>({...x,request_type:'leave',request_data:{leave_type:x.leave_type,start_date:x.start_date,end_date:x.end_date,reason:x.reason}}));throw new Error(d.error||'تعذر تحميل الطلبات')}catch(_){const d=await epApi('/requests');return d.requests||[]}}
async function loadMyRequests(){try{const rows=await fetchSelfRequests();el('myRequestsBody').innerHTML=rows.length?rows.map(r=>`<tr><td>${fmtDate(r.created_at||r.submitted_at)}</td><td>${typeLabel(r.request_type)}</td><td>${statusLabel(r.status)}</td><td><button class="secondary-btn small-btn" type="button" data-request-id="${r.id}">عرض</button></td></tr>`).join(''):'<tr><td colspan="4">لا توجد طلبات</td></tr>';document.querySelectorAll('[data-request-id]').forEach(btn=>btn.onclick=()=>showReqDetails(rows.find(r=>String(r.id)===String(btn.dataset.requestId))))}catch(e){el('myRequestsBody').innerHTML=`<tr><td colspan="4">${e.message}</td></tr>`}}
function showReqDetails(r){if(!r)return;const data=r.request_data||{};el('requestDetailsBox').innerHTML=[detail('نوع الطلب',typeLabel(r.request_type)),detail('الحالة',statusLabel(r.status)),detail('التاريخ',fmtDate(r.created_at||r.submitted_at)),detail('التفاصيل',Object.entries(data).map(([k,v])=>`${k}: ${v}`).join(' | ')||'-')].join('')}

async function initEmployeePortal(){const user=await loadLoggedUser();if(!user)return;const now=new Date();el('portalMonth').value=`${now.getFullYear()}-${String(now.getMonth()+1).padStart(2,'0')}`;el('salaryMonth').value=el('portalMonth').value;el('portalYear').value=now.getFullYear();await loadPortalHome();el('loadAttendanceBtn').addEventListener('click',loadPortalAttendance);el('loadSalaryBtn').addEventListener('click',loadSalarySlip);el('loadMovementsBtn').addEventListener('click',loadMovements);}
async function loadPortalHome(){try{const d=await epApi('/today');const s=d.current_shift||{};el('portalShiftBox').innerHTML=[detail('الشفت الحالي',s.name||'الدوام الافتراضي'),detail('وقت البداية',fmtTime(s.start_time)),detail('وقت النهاية',fmtTime(s.end_time)),detail('الحالة اليوم',d.today_attendance?statusLabel(d.today_attendance.status):'لم يتم التسجيل بعد')].join('')}catch(e){el('portalShiftBox').innerHTML=`<div class="empty-soft">${e.message}</div>`}}
async function loadPortalAttendance(){try{const d=await epApi(`/attendance?month=${el('portalMonth').value}`);const rows=d.attendance||[];el('portalAttendanceBody').innerHTML=rows.length?rows.map(r=>`<tr><td>${fmtDate(r.attendance_date)}</td><td>${fmtTime(r.check_in)}</td><td>${fmtTime(r.check_out)}</td><td>${statusLabel(r.status)} ${r.notes?'- '+r.notes:''}</td></tr>`).join(''):'<tr><td colspan="4">لا توجد سجلات</td></tr>'}catch(e){el('portalAttendanceBody').innerHTML=`<tr><td colspan="4">${e.message}</td></tr>`}}
async function loadSalarySlip(){try{const d=await epApi(`/salary-slip?month=${el('salaryMonth').value}`);const s=d.salary||{};const items=d.items||[];el('salarySlipBox').innerHTML=`<div class="salary-invoice"><div class="invoice-header"><div><span>الشهر</span><strong>${s.salary_month}</strong></div><div><span>الحالة</span><strong>${statusLabel(s.status)}</strong></div><div><span>الصافي</span><strong>${money(s.net_salary)}</strong></div></div><section class="invoice-section"><h3>البنود</h3><div class="invoice-lines">${items.map(i=>`<div class="invoice-line"><div><strong>${i.name}</strong><small>${i.item_type==='income'?'دخل':'اقتطاع'} - ${i.reason||''}</small></div><span class="invoice-line-amount">${money(i.amount)}</span></div>`).join('')}</div></section></div>`}catch(e){el('salarySlipBox').innerHTML=`<div class="empty-soft">${e.message}</div>`}}
async function loadMovements(){try{const rows=await fetchSelfRequests();const year=el('portalYear').value;const filtered=rows.filter(r=>String(r.created_at||r.submitted_at||'').startsWith(year));el('movementsBox').innerHTML=filtered.length?`<div class="table-scroll"><table><thead><tr><th>التاريخ</th><th>النوع</th><th>الحالة</th><th>التفاصيل</th></tr></thead><tbody>${filtered.map(r=>`<tr><td>${fmtDate(r.created_at||r.submitted_at)}</td><td>${typeLabel(r.request_type)}</td><td>${statusLabel(r.status)}</td><td>${Object.entries(r.request_data||{}).map(([k,v])=>`${k}: ${v}`).join(' | ')}</td></tr>`).join('')}</tbody></table></div>`:'<div class="empty-soft">لا توجد حركات</div>'}catch(e){el('movementsBox').innerHTML=`<div class="empty-soft">${e.message}</div>`}}

async function initEmployeeDashboard(){const user=await loadLoggedUser();if(!user)return;if(!isEmployeeOnly(user))return;const main=document.querySelector('.dashboard-main');if(!main)return;document.body.classList.add('employee-only-dashboard');document.querySelector('.header-title-area p').textContent='بوابتك الشخصية للحضور والإعلانات.';const announcementLink=document.querySelector('.header-actions a[href="./announcements.html"]');if(announcementLink){announcementLink.href='./settings.html';announcementLink.querySelector('span').textContent='الإعدادات';announcementLink.title='الإعدادات';announcementLink.setAttribute('aria-label','الإعدادات')}main.querySelectorAll('section').forEach(s=>s.remove());main.insertAdjacentHTML('beforeend',`<section class="content-card today-report-panel"><div class="section-header"><div><span class="page-kicker">شفت اليوم</span><h1>الدوام الحالي</h1><p>تسجيل حضورك وانصرافك من هنا فقط.</p></div><button id="openCheckModal" class="primary-action">تسجيل الحضور والانصراف</button></div><div id="employeeDashShift" class="details-grid"></div></section><section class="content-card announcements-panel"><div class="panel-heading"><div><span class="page-kicker">الإعلانات</span><h2>إعلاناتي</h2><p>آخر الإعلانات الموجهة لك.</p></div></div><div id="employeeDashAnnouncements" class="dashboard-announcements"><div class="empty-soft">جاري التحميل...</div></div></section><div id="checkModal" class="modal-backdrop"><div class="modal-card"><div class="modal-header"><div><h2>تسجيل الحضور والانصراف</h2><p id="liveClock">-</p></div><button class="secondary-btn" id="closeCheckModal">إغلاق</button></div><div class="form-actions"><button id="checkInBtn">تسجيل حضور</button><button id="checkOutBtn" class="secondary-btn">تسجيل انصراف</button></div><p id="checkMsg" class="inline-message"></p></div></div>`);await loadEmployeeDash();}
async function loadEmployeeDash(){try{const d=await epApi('/today');const s=d.current_shift||{};el('employeeDashShift').innerHTML=[detail('الشفت الحالي',s.name||'الدوام الافتراضي'),detail('من',fmtTime(s.start_time)),detail('إلى',fmtTime(s.end_time)),detail('حالة اليوم',d.today_attendance?statusLabel(d.today_attendance.status):'لم يتم التسجيل')].join('');const a=await fetch(`${API_BASE_URL}/announcements/visible`,{headers:{Authorization:`Bearer ${token}`}}).then(r=>r.json()).catch(()=>({announcements:[]}));el('employeeDashAnnouncements').innerHTML=(a.announcements||[]).slice(0,4).map(x=>`<article class="announcement-card"><h3>${x.title}</h3><p>${x.content}</p><div class="announcement-meta"><span>${fmtDate(x.published_at||x.created_at)}</span></div></article>`).join('')||'<div class="empty-soft">لا توجد إعلانات</div>';bindCheckModal()}catch(e){el('employeeDashShift').innerHTML=`<div class="empty-soft">${e.message}</div>`}}
function bindCheckModal(){const modal=el('checkModal');el('openCheckModal').onclick=()=>{modal.classList.add('is-open');tickClock();};el('closeCheckModal').onclick=()=>modal.classList.remove('is-open');el('checkInBtn').onclick=()=>doCheck('checkin');el('checkOutBtn').onclick=()=>doCheck('checkout')}
function tickClock(){const c=el('liveClock');if(!c)return;c.textContent=new Date().toLocaleString('ar-JO',{hour12:false});setTimeout(()=>el('checkModal')?.classList.contains('is-open')&&tickClock(),1000)}
async function doCheck(action){try{const d=await epApi('/attendance',{method:'POST',body:JSON.stringify({action})});el('checkMsg').textContent=d.message;el('checkMsg').className='inline-message success-message';await loadEmployeeDash()}catch(e){el('checkMsg').textContent=e.message;el('checkMsg').className='inline-message error-message'}}
