(()=>{
const byId=(id)=>document.getElementById(id);
const text=(value,fallback='-')=>value===undefined||value===null||value===''?fallback:value;
const date=(value)=>value?String(value).slice(0,10):'-';
const time=(value)=>value?String(value).slice(0,8):'-';
const money=(value)=>Number(value||0).toFixed(2);
const status=(value)=>({present:'حاضر',late:'متأخر',absent:'غائب',early_leave:'خروج مبكر',pending:'قيد الانتظار',approved:'موافق عليه',rejected:'مرفوض',cancelled:'ملغي',needs_info:'يحتاج معلومات',draft:'مسودة',paid:'مدفوع',closed:'مغلق'}[value]||value||'-');
const requestType=(value)=>({leave:'طلب إجازة',exit:'طلب مغادرة',advance:'طلب سلفة',complaint:'شكوى',custom:'طلب مخصص',resignation:'طلب استقالة'}[value]||value||'-');
const detail=(label,value)=>`<div class="detail-item"><span class="detail-label">${label}</span><span class="detail-value">${text(value)}</span></div>`;
const authHeaders=()=>({Authorization:`Bearer ${token}`,'Content-Type':'application/json'});
async function api(path,options={}){const response=await fetch(`${API_BASE_URL}${path}`,{...options,headers:{...authHeaders(),...(options.headers||{})}});const data=await response.json().catch(()=>({}));if(!response.ok)throw new Error(data.error||'تعذر تحميل البيانات');return data;}
async function portal(path,options){return api(`/employee-portal${path}`,options);}
async function ensureUser(){if(typeof loadLoggedUser==='function'){return await loadLoggedUser();}return null;}
function showError(id,message,colspan=4){const el=byId(id);if(!el)return;if(el.tagName==='TBODY')el.innerHTML=`<tr><td colspan="${colspan}">${message}</td></tr>`;else el.innerHTML=`<div class="empty-soft">${message}</div>`;}

async function loadRequests(){try{const data=await portal('/requests');return data.requests||[];}catch(first){try{const data=await api('/leaves');return data.requests||data.leaves||[];}catch(second){throw new Error(`${first.message} / ${second.message}`);}}}
function requestFields(type){if(type==='leave')return `<div class="field-shell"><label class="field-label">نوع الإجازة</label><select id="reqLeaveType"><option value="annual">سنوية</option><option value="sick">مرضية</option><option value="emergency">طارئة</option><option value="unpaid">بدون راتب</option></select></div><div class="field-shell"><label class="field-label">من تاريخ</label><input type="date" id="reqStart"></div><div class="field-shell"><label class="field-label">إلى تاريخ</label><input type="date" id="reqEnd"></div>`;if(type==='exit')return `<div class="field-shell"><label class="field-label">نوع المغادرة</label><select id="reqExitType"><option value="personal">شخصية</option><option value="work">عمل</option><option value="medical">طبية</option></select></div><div class="field-shell"><label class="field-label">التاريخ</label><input type="date" id="reqExitDate"></div><div class="field-shell"><label class="field-label">وقت المغادرة</label><input type="time" id="reqExitTime"></div><div class="field-shell"><label class="field-label">وقت العودة</label><input type="time" id="reqReturnTime"></div>`;if(type==='advance')return `<div class="field-shell"><label class="field-label">المبلغ</label><input type="number" id="reqAmount" min="0" step="0.01"></div><div class="field-shell"><label class="field-label">طريقة الخصم</label><select id="reqDeduction"><option value="one_time">مرة واحدة</option><option value="installments">أقساط</option></select></div><div class="field-shell"><label class="field-label">عدد الأقساط</label><input type="number" id="reqInstallments" min="1" value="1"></div><div class="field-shell"><label class="field-label">بداية الخصم</label><input type="month" id="reqStartMonth"></div>`;return `<div class="field-shell full-width"><label class="field-label">عنوان الطلب</label><input id="reqTitle"></div>`;}
function requestPayload(type){const reason=byId('reqReason')?.value||'';const notes=byId('reqDetails')?.value||'';if(type==='leave')return{leave_type:byId('reqLeaveType')?.value||'annual',start_date:byId('reqStart')?.value,end_date:byId('reqEnd')?.value,reason,notes};if(type==='exit')return{exit_type:byId('reqExitType')?.value||'personal',exit_date:byId('reqExitDate')?.value,exit_time:byId('reqExitTime')?.value,return_time:byId('reqReturnTime')?.value,reason,notes};if(type==='advance')return{amount:Number(byId('reqAmount')?.value||0),deduction_method:byId('reqDeduction')?.value||'one_time',installments_count:Number(byId('reqInstallments')?.value||1),deduction_start_month:byId('reqStartMonth')?.value,reason,notes};return{title:byId('reqTitle')?.value||requestType(type),reason,details:notes,notes};}
async function renderRequests(){const body=byId('myRequestsBody');if(!body)return;try{const rows=await loadRequests();body.innerHTML=rows.length?rows.map((r)=>`<tr><td>${date(r.created_at||r.submitted_at)}</td><td>${requestType(r.request_type)}</td><td>${status(r.status)}</td><td><button class="secondary-btn small-btn" type="button" data-request-id="${r.id}">عرض</button></td></tr>`).join(''):'<tr><td colspan="4">لا توجد طلبات لهذا الحساب</td></tr>';document.querySelectorAll('[data-request-id]').forEach((btn)=>{btn.onclick=()=>{const r=rows.find((x)=>String(x.id)===String(btn.dataset.requestId));const data=r?.request_data||{};const box=byId('requestDetailsBox');if(box)box.innerHTML=[detail('نوع الطلب',requestType(r?.request_type)),detail('الحالة',status(r?.status)),detail('التاريخ',date(r?.created_at||r?.submitted_at)),detail('التفاصيل',Object.entries(data).map(([k,v])=>`${k}: ${v}`).join(' | ')||'-')].join('');};});}catch(error){showError('myRequestsBody',error.message,4);}}
window.initMyRequests=async()=>{await ensureUser();const type=byId('requestType');const dynamic=byId('dynamicFields');const form=byId('requestForm');if(type&&dynamic){dynamic.innerHTML=requestFields(type.value);type.onchange=()=>{dynamic.innerHTML=requestFields(type.value);};}await renderRequests();if(form&&type){form.onsubmit=async(event)=>{event.preventDefault();const msg=byId('requestMsg');try{const data=await api('/leaves',{method:'POST',body:JSON.stringify({request_type:type.value,status:'pending',request_data:requestPayload(type.value)})});if(msg){msg.textContent=data.message||'تم إرسال الطلب';msg.className='inline-message success-message';}form.reset();if(dynamic)dynamic.innerHTML=requestFields(type.value);await renderRequests();}catch(error){if(msg){msg.textContent=error.message;msg.className='inline-message error-message';}}};}};

async function renderAttendance(){const body=byId('portalAttendanceBody');if(!body)return;try{const selectedMonth=byId('portalMonth')?.value||new Date().toISOString().slice(0,7);const data=await portal(`/attendance?month=${selectedMonth}`);const rows=data.attendance||[];body.innerHTML=rows.length?rows.map((r)=>`<tr><td>${date(r.attendance_date)}</td><td>${time(r.check_in)}</td><td>${time(r.check_out)}</td><td>${status(r.status)}${Number(r.late_minutes||0)>0?' - تأخير '+r.late_minutes+' دقيقة':''}${Number(r.overtime_minutes||0)>0?' - إضافي '+r.overtime_minutes+' دقيقة':''}${r.notes?' - '+r.notes:''}</td></tr>`).join(''):'<tr><td colspan="4">لا توجد سجلات حضور لهذا الشهر</td></tr>';}catch(error){showError('portalAttendanceBody',error.message,4);}}
async function renderSalary(){const box=byId('salarySlipBox');if(!box)return;try{const selectedMonth=byId('salaryMonth')?.value||new Date().toISOString().slice(0,7);const data=await portal(`/salary-slip?month=${selectedMonth}`);const salary=data.salary||{};const items=data.items||[];box.innerHTML=`<div class="salary-invoice"><div class="invoice-header"><div><span>الشهر</span><strong>${text(salary.salary_month)}</strong></div><div><span>الحالة</span><strong>${status(salary.status)}</strong></div><div><span>الصافي</span><strong>${money(salary.net_salary)}</strong></div></div><section class="invoice-section"><h3>البنود</h3><div class="invoice-lines">${items.length?items.map((item)=>`<div class="invoice-line"><div><strong>${item.name}</strong><small>${item.item_type==='income'?'دخل':'اقتطاع'} - ${item.reason||''}</small></div><span class="invoice-line-amount">${money(item.amount)}</span></div>`).join(''):'<div class="empty-soft">لا توجد بنود ظاهرة</div>'}</div></section></div>`;}catch(error){showError('salarySlipBox',error.message);}}
async function renderMovements(){const box=byId('movementsBox');if(!box)return;try{const selectedYear=String(byId('portalYear')?.value||new Date().getFullYear());const requests=(await loadRequests()).filter((r)=>String(r.created_at||r.submitted_at||'').startsWith(selectedYear)).map((r)=>({date:date(r.created_at||r.submitted_at),type:requestType(r.request_type),status:status(r.status),details:Object.entries(r.request_data||{}).map(([k,v])=>`${k}: ${v}`).join(' | ')}));let attendanceRows=[];for(let month=1;month<=12;month++){try{const data=await portal(`/attendance?month=${selectedYear}-${String(month).padStart(2,'0')}`);attendanceRows.push(...(data.attendance||[]));}catch(_){}}
const attendanceMovements=attendanceRows.filter((r)=>Number(r.late_minutes||0)>0||Number(r.overtime_minutes||0)>0||['late','early_leave','absent'].includes(r.status)).map((r)=>({date:date(r.attendance_date),type:Number(r.overtime_minutes||0)>0?'عمل إضافي':status(r.status),status:status(r.status),details:`تأخير: ${r.late_minutes||0} دقيقة | إضافي: ${r.overtime_minutes||0} دقيقة ${r.overtime_type?'- '+r.overtime_type:''}`}));const rows=[...requests,...attendanceMovements].sort((a,b)=>String(b.date).localeCompare(String(a.date)));box.innerHTML=rows.length?`<div class="table-scroll"><table><thead><tr><th>التاريخ</th><th>النوع</th><th>الحالة</th><th>التفاصيل</th></tr></thead><tbody>${rows.map((row)=>`<tr><td>${row.date}</td><td>${row.type}</td><td>${row.status}</td><td>${row.details||'-'}</td></tr>`).join('')}</tbody></table></div>`:'<div class="empty-soft">لا توجد حركات لهذه السنة</div>';}catch(error){showError('movementsBox',error.message);}}
window.initEmployeePortal=async()=>{await ensureUser();const now=new Date();if(byId('portalMonth'))byId('portalMonth').value=`${now.getFullYear()}-${String(now.getMonth()+1).padStart(2,'0')}`;if(byId('salaryMonth'))byId('salaryMonth').value=byId('portalMonth')?.value||new Date().toISOString().slice(0,7);if(byId('portalYear'))byId('portalYear').value=now.getFullYear();try{const data=await portal('/today');const shift=data.current_shift||{};const box=byId('portalShiftBox');if(box)box.innerHTML=[detail('الشفت الحالي',shift.name||'الدوام الافتراضي'),detail('وقت البداية',time(shift.start_time)),detail('وقت النهاية',time(shift.end_time)),detail('الحالة اليوم',data.today_attendance?status(data.today_attendance.status):'لم يتم التسجيل بعد')].join('');}catch(error){showError('portalShiftBox',error.message);}if(byId('loadAttendanceBtn'))byId('loadAttendanceBtn').onclick=renderAttendance;if(byId('loadSalaryBtn'))byId('loadSalaryBtn').onclick=renderSalary;if(byId('loadMovementsBtn'))byId('loadMovementsBtn').onclick=renderMovements;await renderAttendance();await renderSalary();await renderMovements();};

window.initMyProfile=async()=>{await ensureUser();try{const data=await portal('/profile');const profile=data.profile||{};const shift=data.current_shift||{};if(byId('profilePersonal'))byId('profilePersonal').innerHTML=[detail('تاريخ الميلاد',date(profile.birth_date||profile.date_of_birth)),detail('تاريخ التعيين',date(profile.hire_date)),detail('الجنسية',profile.nationality||'-'),detail('الجنس',profile.gender||'-')].join('');if(byId('profileLeaves'))byId('profileLeaves').innerHTML=[detail('الرصيد الحالي',profile.leave_balance_current??14),detail('الأيام المستهلكة',profile.leave_days_consumed??0),detail('المتبقي حتى اليوم',profile.leave_balance_remaining??0)].join('');if(byId('profileWork'))byId('profileWork').innerHTML=[detail('القسم الرئيسي',profile.department_name||'-'),detail('القسم الفرعي',(data.sub_departments||[]).map((x)=>x.name).join('، ')||'-'),detail('المسمى الوظيفي',profile.job_title_label||profile.job_title_name||profile.job_title||'-'),detail('الشفت الحالي',shift.name||'الدوام الافتراضي')].join('');if(byId('profileContact'))byId('profileContact').innerHTML=[detail('رقم الهاتف',profile.phone||'-'),detail('البريد الإلكتروني',profile.email||'-')].join('');}catch(error){showError('profilePersonal',error.message);}};

window.initEmployeeDashboard=async()=>{const user=await ensureUser();const roles=user?.roles||[];const permissions=user?.permissions||[];const employeeOnly=roles.includes('employee')&&!roles.includes('admin')&&!permissions.includes('system.admin');if(!employeeOnly){if(typeof revealProtectedShell==='function')revealProtectedShell();return;}const main=document.querySelector('.dashboard-main');if(!main){if(typeof revealProtectedShell==='function')revealProtectedShell();return;}document.body.classList.add('employee-only-dashboard');main.querySelectorAll('section').forEach((section)=>section.remove());main.insertAdjacentHTML('beforeend',`<section class="content-card today-report-panel"><div class="section-header"><div><span class="page-kicker">شفت اليوم</span><h1>الدوام الحالي</h1><p>تسجيل حضورك وانصرافك من هنا فقط.</p></div><button id="openCheckModal" class="primary-action">تسجيل الحضور والانصراف</button></div><div id="employeeDashShift" class="details-grid"></div></section><section class="content-card announcements-panel"><div class="panel-heading"><div><span class="page-kicker">الإعلانات</span><h2>إعلاناتي</h2><p>آخر الإعلانات الموجهة لك.</p></div></div><div id="employeeDashAnnouncements" class="dashboard-announcements"><div class="empty-soft">جاري تحميل الإعلانات...</div></div></section><div id="checkModal" class="modal-backdrop"><div class="modal-card"><div class="modal-header"><div><h2>تسجيل الحضور والانصراف</h2><p id="liveClock">-</p></div><button class="secondary-btn" id="closeCheckModal">إغلاق</button></div><div class="form-actions"><button id="checkInBtn">تسجيل حضور</button><button id="checkOutBtn" class="secondary-btn">تسجيل انصراف</button></div><p id="checkMsg" class="inline-message"></p></div></div>`);if(typeof revealProtectedShell==='function')revealProtectedShell();
async function reloadToday(){try{const data=await portal('/today');const shift=data.current_shift||{};const box=byId('employeeDashShift');if(box)box.innerHTML=[detail('الشفت الحالي',shift.name||'الدوام الافتراضي'),detail('من',time(shift.start_time)),detail('إلى',time(shift.end_time)),detail('حالة اليوم',data.today_attendance?status(data.today_attendance.status):'لم يتم التسجيل')].join('');}catch(error){showError('employeeDashShift',error.message);}}
async function reloadAnnouncements(){const box=byId('employeeDashAnnouncements');if(!box)return;try{const data=await api('/announcements/visible');const rows=data.announcements||[];box.innerHTML=rows.length?rows.slice(0,5).map((item)=>`<article class="announcement-card"><h3>${item.title}</h3><p>${item.content||''}</p><div class="announcement-meta"><span>${date(item.published_at||item.created_at)}</span></div></article>`).join(''):'<div class="empty-soft">لا توجد إعلانات موجهة لك</div>';}catch(error){box.innerHTML=`<div class="empty-soft">${error.message}</div>`;}}
await reloadToday();await reloadAnnouncements();if(byId('openCheckModal'))byId('openCheckModal').onclick=()=>byId('checkModal')?.classList.add('is-open');if(byId('closeCheckModal'))byId('closeCheckModal').onclick=()=>byId('checkModal')?.classList.remove('is-open');if(byId('checkInBtn'))byId('checkInBtn').onclick=async()=>{const msg=byId('checkMsg');try{const data=await portal('/attendance',{method:'POST',body:JSON.stringify({action:'checkin'})});if(msg){msg.textContent=data.message;msg.className='inline-message success-message';}await reloadToday();}catch(error){if(msg){msg.textContent=error.message;msg.className='inline-message error-message';}}};if(byId('checkOutBtn'))byId('checkOutBtn').onclick=async()=>{const msg=byId('checkMsg');try{const data=await portal('/attendance',{method:'POST',body:JSON.stringify({action:'checkout'})});if(msg){msg.textContent=data.message;msg.className='inline-message success-message';}await reloadToday();}catch(error){if(msg){msg.textContent=error.message;msg.className='inline-message error-message';}}};};
})();
