const bodyEl=document.getElementById('employeesTableBody');
const cardsEl=document.getElementById('employeesCards');
const form=document.getElementById('employeeForm');
const modal=document.getElementById('employeeModal');
const msgEl=document.getElementById('formMessage');
const mainDepSel=document.getElementById('department_id');
const subDepSel=document.getElementById('sub_department_id');
const jobTitleSel=document.getElementById('job_title_id');
const jobTitlePreviewBox=document.getElementById('jobTitlePreviewBox');
const jobTitlePreviewText=document.getElementById('jobTitlePreviewText');
const q=document.getElementById('employeeSearchInput');
const depFilter=document.getElementById('departmentFilter');
const jobTitleFilter=document.getElementById('jobTitleFilter');
const roleFilter=document.getElementById('roleFilter');
const stFilter=document.getElementById('statusFilter');
const countEl=document.getElementById('employeesCountText');
let employees=[];let departments=[];let jobTitles=[];let permissionDefinitions=[];let renderTimer=null;
const roleLabels={employee:'موظف',manager:'مدير قسم',hr:'الموارد البشرية',finance:'المالية',admin:'مدير النظام'};
function msg(t,b){if(!msgEl)return;msgEl.textContent=t;msgEl.className='inline-message '+(b?'error-message':'success-message')}
function v(id){return(document.getElementById(id)?.value||'').trim()}
function sv(id,x){let e=document.getElementById(id);if(e)e.value=x??''}
function initials(name=''){return name.trim().split(/\s+/).slice(0,2).map(x=>x[0]).join('')||'م'}
function checkedRoles(){return Array.from(document.querySelectorAll('[name="roleCheck"]:checked')).map(x=>x.value)}
function setCheckedRoles(roles=[]){let list=Array.isArray(roles)?roles:[];if(!list.length)list=['employee'];document.querySelectorAll('[name="roleCheck"]').forEach(c=>c.checked=list.includes(c.value))}
function directPermissions(){return v('direct_permissions').split(',').map(x=>x.trim()).filter(Boolean)}
function childrenOf(parentId){return departments.filter(d=>String(d.parent_id||'')===String(parentId||''))}
function roots(){return departments.filter(d=>!d.parent_id)}
function permissionLabel(key){return permissionDefinitions.find(p=>p.key===key)?.label||key}
function debounce(fn,ms=180){return(...args)=>{clearTimeout(renderTimer);renderTimer=setTimeout(()=>fn(...args),ms)}}
async function fetchJson(url,opt={}){let r=await fetch(url,{headers:{Authorization:`Bearer ${token}`,'Content-Type':'application/json'},...opt});let d=await r.json().catch(()=>({}));if(!r.ok)throw new Error(d.error||'فشل الطلب');return d}
function openEmployeeModal(){modal?.classList.add('is-open');modal?.setAttribute('aria-hidden','false');document.body.classList.add('no-scroll')}
function closeEmployeeModal(){modal?.classList.remove('is-open');modal?.setAttribute('aria-hidden','true');document.body.classList.remove('no-scroll')}
async function initEmployees(){let u=await loadLoggedUser();if(!u||(!hasAnyPermission(['employees.view'])&&!hasAnyPermission(['employees.view.self']))){location.href='./dashboard.html';return}await Promise.all([loadDepartments(),loadJobTitles()]);await loadEmployees()}
async function loadDepartments(){try{let d=await fetchJson(`${API_BASE_URL}/departments`);departments=d.departments||[]}catch(e){departments=[]}let rootOpts=roots().map(x=>`<option value="${x.id}">${x.name}</option>`).join('');mainDepSel.innerHTML='<option value="">اختر القسم الرئيسي</option>'+rootOpts;depFilter.innerHTML='<option value="">كل الأقسام</option>'+departments.map(x=>`<option value="${x.id}">${x.parent_name?x.parent_name+' / ':''}${x.name}</option>`).join('');renderSubDepartments()}
async function loadJobTitles(){try{let d=await fetchJson(`${API_BASE_URL}/permissions/job-titles`);jobTitles=(d.job_titles||[]).filter(j=>j.status==='active');permissionDefinitions=d.permissions||[];renderJobTitlesSelect();if(jobTitleFilter)jobTitleFilter.innerHTML='<option value="">كل المسميات</option>'+jobTitles.map(j=>`<option value="${j.id}">${j.name}</option>`).join('')}catch(e){jobTitles=[];permissionDefinitions=[];if(jobTitleSel)jobTitleSel.innerHTML='<option value="">تعذر تحميل المسميات الوظيفية</option>'}}
function renderJobTitlesSelect(selected=''){if(!jobTitleSel)return;jobTitleSel.innerHTML='<option value="">اختر المسمى الوظيفي</option>'+jobTitles.map(j=>`<option value="${j.id}" ${String(selected)===String(j.id)?'selected':''}>${j.name}</option>`).join('');renderJobTitlePreview()}
function renderJobTitlePreview(){let id=v('job_title_id');let j=jobTitles.find(x=>String(x.id)===String(id));if(!j){jobTitlePreviewBox.style.display='none';jobTitlePreviewText.textContent='';return}let perms=Array.isArray(j.default_permissions)?j.default_permissions:[];let sample=perms.slice(0,6).map(permissionLabel).join('، ');jobTitlePreviewBox.style.display='block';jobTitlePreviewText.textContent=perms.length?` الصلاحيات الافتراضية: ${sample}${perms.length>6?'، وغيرها':''}.`:' هذا المسمى لا يحتوي على صلاحيات افتراضية بعد.'}
function renderSubDepartments(selected=''){let parent=mainDepSel.value;let list=childrenOf(parent);if(!parent){subDepSel.innerHTML='<option value="">اختر القسم الرئيسي أولاً</option>';subDepSel.disabled=true;return}if(!list.length){subDepSel.innerHTML='<option value="">لا توجد أقسام فرعية لهذا القسم</option>';subDepSel.disabled=true;return}subDepSel.disabled=false;subDepSel.innerHTML='<option value="">بدون قسم إضافي</option>'+list.map(x=>`<option value="${x.id}" ${String(selected)===String(x.id)?'selected':''}>${x.name}</option>`).join('')}
async function loadEmployees(){countEl.textContent='جاري تحميل البيانات...';try{let d=await fetchJson(`${API_BASE_URL}/employees?limit=200`);employees=d.employees||[];renderEmployees()}catch(e){bodyEl.innerHTML=`<tr><td colspan="9">${e.message||'تعذر تحميل البيانات'}</td></tr>`;countEl.textContent='تعذر تحميل البيانات'}}
function filtered(){let s=q.value.trim().toLowerCase(),dep=depFilter.value,st=stFilter.value,jt=jobTitleFilter?.value||'',role=roleFilter?.value||'';return employees.filter(e=>{let text=e._searchText;if(!text){text=[e.employee_number,e.full_name,e.phone,e.email,e.job_title,e.job_title_name,e.department_name,...((e.additional_departments||[]).map(x=>x.department_name))].filter(Boolean).join(' ').toLowerCase();e._searchText=text}let depIds=e._depIds;if(!depIds){depIds=(e.departments||[]).map(x=>String(x.department_id));e._depIds=depIds}let roles=e.roles||e.account?.roles||[];let jobId=String(e.job_title_id||findJobTitleId(e)||'');return(!s||text.includes(s))&&(!dep||String(e.department_id)===dep||depIds.includes(dep))&&(!jt||jobId===String(jt))&&(!role||roles.includes(role))&&(!st||(st==='active'&&e.is_active)||(st==='inactive'&&!e.is_active)||e.status===st)})}
function updateStats(){let total=employees.length;let active=employees.filter(e=>e.is_active).length;let inactive=total-active;let withoutDep=employees.filter(e=>!(e.primary_department?.department_name||e.department_name||e.department_id)).length;let withoutJob=employees.filter(e=>!(e.job_title||e.job_title_name||e.job_title_id)).length;svText('statTotalEmployees',total);svText('statActiveEmployees',active);svText('statInactiveEmployees',inactive);svText('statWithoutDepartment',withoutDep);svText('statWithoutJobTitle',withoutJob)}
function svText(id,x){let el=document.getElementById(id);if(el)el.textContent=x}
function loginBadge(e){let enabled=e.is_login_enabled&&e.account_status!=='disabled'&&e.account_status!=='locked';return `<span class="mini-badge ${enabled?'status-active':'status-inactive'}">${enabled?'الدخول مفعّل':'الدخول معطّل'}</span>`}
function statusBadge(e){return `<span class="mini-badge ${e.is_active?'status-active':'status-inactive'}">${e.is_active?'نشط':'غير نشط'}</span>`}
function rolesHtml(e){let roles=e.roles||e.account?.roles||['employee'];return `<div class="role-pills">${roles.slice(0,3).map(r=>`<span class="mini-badge">${roleLabels[r]||r}</span>`).join('')}${roles.length>3?`<span class="mini-badge">+${roles.length-3}</span>`:''}</div>`}
function employeeSummary(e){return {name:e.full_name||'-',num:e.employee_number||'-',job:e.job_title||e.job_title_name||'-',dep:e.primary_department?.department_name||e.department_name||'-',updated:e.updated_at?new Date(e.updated_at).toLocaleDateString('ar-JO'):'-'}}
function renderEmployees(){updateStats();let list=filtered();countEl.textContent=`عرض ${list.length} من أصل ${employees.length} موظف`;if(!list.length){bodyEl.innerHTML='<tr><td colspan="9">لا توجد نتائج مطابقة</td></tr>';if(cardsEl)cardsEl.innerHTML='<div class="empty-list">لا توجد نتائج مطابقة</div>';return}let rows=list.slice(0,200).map(e=>{let s=employeeSummary(e);return `<tr><td><div class="employee-name-cell"><span class="employee-avatar">${initials(s.name)}</span><span><strong>${s.name}</strong><small>${s.num}</small></span></div></td><td>${s.num}</td><td>${s.dep}</td><td>${s.job}</td><td>${statusBadge(e)}</td><td>${loginBadge(e)}</td><td>${rolesHtml(e)}</td><td>${s.updated}</td><td><div class="row-actions"><button class="secondary-btn small-btn" data-a="view" data-id="${e.id}">عرض</button><button class="edit-btn small-btn" data-a="edit" data-id="${e.id}">تعديل</button><button class="danger-btn small-btn" data-a="del" data-id="${e.id}">حذف</button></div></td></tr>`}).join('');bodyEl.innerHTML=rows;if(cardsEl)cardsEl.innerHTML=list.slice(0,200).map(e=>{let s=employeeSummary(e);return `<article class="employee-card"><div class="employee-card-head"><span class="employee-avatar">${initials(s.name)}</span><div><h3>${s.name}</h3><span class="mini-badge">${s.num}</span></div></div><div class="employee-card-meta"><div><small>المسمى الوظيفي</small><strong>${s.job}</strong></div><div><small>القسم الأساسي</small><strong>${s.dep}</strong></div><div><small>الحالة</small>${statusBadge(e)}</div><div><small>الدخول</small>${loginBadge(e)}</div></div><div>${rolesHtml(e)}</div><div class="employee-card-actions"><button class="secondary-btn small-btn" data-a="view" data-id="${e.id}">عرض</button><button class="edit-btn small-btn" data-a="edit" data-id="${e.id}">تعديل</button></div></article>`}).join('')}
function findMainAndSub(e){let memberships=e.departments||[];let primary=e.primary_department||memberships.find(x=>x.is_primary);let sub=memberships.find(x=>!x.is_primary);if(primary&&primary.parent_id){sub=primary;let parent=departments.find(d=>String(d.id)===String(primary.parent_id));return{main:parent?.id||'',sub:primary.department_id}}return{main:primary?.department_id||e.department_id||'',sub:sub?.department_id||''}}
function findJobTitleId(e){if(e.job_title_id)return e.job_title_id;let byName=jobTitles.find(j=>j.name===e.job_title||j.name===e.job_title_name);return byName?.id||''}
function editEmployee(id){let e=employees.find(x=>String(x.id)===String(id));if(!e)return;let ds=findMainAndSub(e);sv('employeeId',e.id);sv('employee_number',e.employee_number||e.national_id);sv('full_name',e.full_name);sv('national_id',e.national_id);sv('phone',e.phone);sv('email',e.email);sv('address',e.address);sv('password','');sv('is_login_enabled',String(e.is_login_enabled!==false));sv('account_status',e.account_status||'active');sv('job_title_id',findJobTitleId(e));renderJobTitlePreview();sv('department_id',ds.main);renderSubDepartments(ds.sub);sv('hire_date',e.hire_date?e.hire_date.split('T')[0]:'');sv('employment_type',e.employment_type||'full_time');sv('is_active',String(e.is_active));sv('basic_salary',e.basic_salary||0);sv('social_security_enabled',String(e.social_security_enabled!==false));sv('social_security_rate',e.social_security_rate||7.5);setCheckedRoles(e.roles||e.account?.roles||['employee']);sv('direct_permissions',(e.permissions||e.account?.permissions||[]).join(', '));document.getElementById('employeeFormTitle').textContent='تعديل موظف';openEmployeeModal()}
function resetForm(){form.reset();sv('employeeId','');sv('social_security_rate','7.5');sv('account_status','active');sv('is_login_enabled','true');sv('job_title_id','');renderJobTitlePreview();setCheckedRoles(['employee']);renderSubDepartments();document.getElementById('employeeFormTitle').textContent='إضافة موظف';msg('',false)}
form.addEventListener('submit',async ev=>{ev.preventDefault();let submitBtn=form.querySelector('button[type="submit"]');submitBtn.disabled=true;submitBtn.textContent='يتم الحفظ...';let main=v('department_id');let sub=v('sub_department_id');let deps=[];if(main)deps.push({department_id:main,is_primary:true,status:'active'});if(sub&&sub!==main)deps.push({department_id:sub,is_primary:false,status:'active'});let id=v('employeeId');let loginEnabled=v('is_login_enabled')==='true';let jobTitle=jobTitles.find(j=>String(j.id)===String(v('job_title_id')));let data={full_name:v('full_name'),employee_number:v('employee_number'),national_id:v('national_id')||v('employee_number'),phone:v('phone'),email:v('email'),address:v('address'),password:v('password'),is_login_enabled:loginEnabled,account_status:v('account_status'),roles:checkedRoles(),permissions:directPermissions(),job_title_id:v('job_title_id')?Number(v('job_title_id')):null,job_title:jobTitle?.name||'',department_id:main||null,departments:deps,hire_date:v('hire_date')||null,employment_type:v('employment_type'),is_active:v('is_active')==='true',status:v('is_active')==='true'?'active':'inactive',basic_salary:Number(v('basic_salary')||0),social_security_enabled:v('social_security_enabled')==='true',social_security_rate:Number(v('social_security_rate')||7.5)};if(!data.full_name||!data.employee_number||!data.job_title_id||!main){msg('الاسم ورقم الموظف والمسمى الوظيفي والقسم الأساسي مطلوبة',true);submitBtn.disabled=false;submitBtn.textContent='حفظ الموظف';return}if(!id&&loginEnabled&&!data.password){msg('كلمة المرور مطلوبة عند تفعيل الدخول للنظام',true);submitBtn.disabled=false;submitBtn.textContent='حفظ الموظف';return}try{let d=await fetchJson(id?`${API_BASE_URL}/employees/${id}`:`${API_BASE_URL}/employees`,{method:id?'PUT':'POST',body:JSON.stringify(data)});msg(d.message||'تم حفظ الموظف');resetForm();closeEmployeeModal();await loadEmployees()}catch(e){msg(e.message||'تعذر حفظ الموظف',true)}finally{submitBtn.disabled=false;submitBtn.textContent='حفظ الموظف'}});
async function removeEmployee(id){if(!confirm('هل أنت متأكد من حذف الموظف؟'))return;let r=await fetch(`${API_BASE_URL}/employees/${id}`,{method:'DELETE',headers:{Authorization:`Bearer ${token}`}});let d=await r.json();if(r.status===409){let action=confirm((d.error||'لا يمكن حذف هذا الموظف نهائيًا لأنه مرتبط ببيانات أخرى. يمكنك تعطيله أو أرشفته بدلاً من الحذف.')+'\nموافق للتعطيل، إلغاء للأرشفة')?'disable':'archive';let rr=await fetch(`${API_BASE_URL}/employees/${id}/${action}`,{method:'PATCH',headers:{Authorization:`Bearer ${token}`}});let dd=await rr.json();msg(dd.message||dd.error,!rr.ok);await loadEmployees();return}msg(d.message||d.error,!r.ok);await loadEmployees()}
function handleListClick(e){let b=e.target.closest('button');if(!b)return;let id=b.dataset.id;if(b.dataset.a==='view')location.href=`./employee-profile.html?id=${id}`;if(b.dataset.a==='edit')editEmployee(id);if(b.dataset.a==='del')removeEmployee(id)}
bodyEl.addEventListener('click',handleListClick);cardsEl?.addEventListener('click',handleListClick);
const debouncedRender=debounce(renderEmployees,180);
mainDepSel.addEventListener('change',()=>renderSubDepartments());if(jobTitleSel)jobTitleSel.addEventListener('change',renderJobTitlePreview);document.getElementById('cancelEditBtn').addEventListener('click',()=>{resetForm();closeEmployeeModal()});document.querySelectorAll('[data-close-employee-modal]').forEach(x=>x.addEventListener('click',()=>{resetForm();closeEmployeeModal()}));document.getElementById('openEmployeeModalBtn')?.addEventListener('click',()=>{resetForm();openEmployeeModal()});q.addEventListener('input',debouncedRender);depFilter.addEventListener('change',renderEmployees);stFilter.addEventListener('change',renderEmployees);jobTitleFilter?.addEventListener('change',renderEmployees);roleFilter?.addEventListener('change',renderEmployees);document.getElementById('applyEmployeesFilterBtn')?.addEventListener('click',renderEmployees);document.getElementById('clearEmployeesFilterBtn')?.addEventListener('click',()=>{q.value='';depFilter.value='';stFilter.value='';if(jobTitleFilter)jobTitleFilter.value='';if(roleFilter)roleFilter.value='';renderEmployees()});document.getElementById('refreshEmployeesBtn').addEventListener('click',loadEmployees);document.getElementById('exportEmployeesBtn').addEventListener('click',()=>msg('تم تجهيز البيانات للتصدير من التقارير'));
initEmployees();
