const bodyEl=document.getElementById('employeesTableBody');
const form=document.getElementById('employeeForm');
const msgEl=document.getElementById('formMessage');
const mainDepSel=document.getElementById('department_id');
const subDepSel=document.getElementById('sub_department_id');
const q=document.getElementById('employeeSearchInput');
const depFilter=document.getElementById('departmentFilter');
const stFilter=document.getElementById('statusFilter');
const countEl=document.getElementById('employeesCountText');
let employees=[];
let departments=[];
function msg(t,b){msgEl.textContent=t;msgEl.className='inline-message '+(b?'error-message':'success-message')}
function v(id){return(document.getElementById(id)?.value||'').trim()}
function sv(id,x){let e=document.getElementById(id);if(e)e.value=x??''}
function childrenOf(parentId){return departments.filter(d=>String(d.parent_id||'')===String(parentId||''))}
function roots(){return departments.filter(d=>!d.parent_id)}
async function initEmployees(){let u=await loadLoggedUser();if(!u||u.role==='employee'){location.href='./dashboard.html';return}await loadDepartments();await loadEmployees()}
async function loadDepartments(){let r=await fetch(`${API_BASE_URL}/departments`,{headers:{Authorization:`Bearer ${token}`}});let d=await r.json();departments=r.ok?d.departments||[]:[];let rootOpts=roots().map(x=>`<option value="${x.id}">${x.name}</option>`).join('');mainDepSel.innerHTML='<option value="">اختر القسم الرئيسي</option>'+rootOpts;depFilter.innerHTML='<option value="">كل الأقسام</option>'+departments.map(x=>`<option value="${x.id}">${x.parent_name?x.parent_name+' / ':''}${x.name}</option>`).join('');renderSubDepartments()}
function renderSubDepartments(selected=''){let parent=mainDepSel.value;let list=childrenOf(parent);subDepSel.innerHTML='<option value="">بدون قسم فرعي</option>'+list.map(x=>`<option value="${x.id}" ${String(selected)===String(x.id)?'selected':''}>${x.name}</option>`).join('');subDepSel.disabled=!parent||!list.length}
async function loadEmployees(){countEl.textContent='جاري تحميل البيانات...';let r=await fetch(`${API_BASE_URL}/employees`,{headers:{Authorization:`Bearer ${token}`}});let d=await r.json();if(!r.ok){bodyEl.innerHTML=`<tr><td colspan="9">${d.error||'تعذر تحميل البيانات'}</td></tr>`;countEl.textContent='تعذر تحميل البيانات';return}employees=d.employees||[];renderEmployees()}
function filtered(){let s=q.value.trim().toLowerCase(),dep=depFilter.value,st=stFilter.value;return employees.filter(e=>{let text=[e.employee_number,e.full_name,e.phone,e.email,e.job_title,e.department_name,...((e.additional_departments||[]).map(x=>x.department_name))].filter(Boolean).join(' ').toLowerCase();let depIds=(e.departments||[]).map(x=>String(x.department_id));return(!s||text.includes(s))&&(!dep||String(e.department_id)===dep||depIds.includes(dep))&&(!st||(st==='active'&&e.is_active)||(st==='inactive'&&!e.is_active)||e.status===st)})}
function subLabel(e){let sub=(e.additional_departments||[])[0];return sub?`<span class="soft-badge">${sub.department_name}</span>`:'-'}
function renderEmployees(){let list=filtered();countEl.textContent=`عرض ${list.length} من أصل ${employees.length} موظف`;if(!list.length){bodyEl.innerHTML='<tr><td colspan="9">لا توجد نتائج مطابقة</td></tr>';return}bodyEl.innerHTML='';list.forEach(e=>{let tr=document.createElement('tr');tr.innerHTML=`<td>${e.id}</td><td>${e.full_name}</td><td>${e.phone||'-'}</td><td>${e.email||'-'}</td><td>${e.job_title||'-'}</td><td>${e.primary_department?.department_name||e.department_name||'-'}</td><td>${subLabel(e)}</td><td><span class="status-badge ${e.is_active?'active-badge':'inactive-badge'}">${e.is_active?'نشط':'غير نشط'}</span></td><td><div class="row-actions"><button class="secondary-btn small-btn" data-a="view" data-id="${e.id}">عرض</button><button class="edit-btn small-btn" data-a="edit" data-id="${e.id}">تعديل</button><button class="danger-btn small-btn" data-a="del" data-id="${e.id}">حذف</button></div></td>`;bodyEl.appendChild(tr)})}
function findMainAndSub(e){let memberships=e.departments||[];let primary=e.primary_department||memberships.find(x=>x.is_primary);let sub=memberships.find(x=>!x.is_primary);if(primary&&primary.parent_id){sub=primary;let parent=departments.find(d=>String(d.id)===String(primary.parent_id));return{main:parent?.id||'',sub:primary.department_id}}return{main:primary?.department_id||e.department_id||'',sub:sub?.department_id||''}}
function editEmployee(id){let e=employees.find(x=>String(x.id)===String(id));if(!e)return;let ds=findMainAndSub(e);sv('employeeId',e.id);sv('full_name',e.full_name);sv('national_id',e.employee_number||e.national_id);sv('phone',e.phone);sv('email',e.email);sv('address',e.address);sv('job_title',e.job_title);sv('department_id',ds.main);renderSubDepartments(ds.sub);sv('hire_date',e.hire_date?e.hire_date.split('T')[0]:'');sv('employment_type',e.employment_type||'full_time');sv('is_active',String(e.is_active));document.getElementById('employeeFormTitle').textContent='تعديل موظف';scrollTo({top:0,behavior:'smooth'})}
function resetForm(){form.reset();sv('employeeId','');renderSubDepartments();document.getElementById('employeeFormTitle').textContent='إضافة موظف'}
form.addEventListener('submit',async ev=>{ev.preventDefault();let main=v('department_id');let sub=v('sub_department_id');let deps=[];if(main)deps.push({department_id:main,is_primary:true,status:'active'});if(sub&&sub!==main)deps.push({department_id:sub,is_primary:false,status:'active'});let data={full_name:v('full_name'),employee_number:v('national_id'),national_id:v('national_id'),phone:v('phone'),email:v('email'),address:v('address'),job_title:v('job_title'),department_id:main||null,departments:deps,hire_date:v('hire_date')||null,employment_type:v('employment_type'),is_active:v('is_active')==='true',status:v('is_active')==='true'?'active':'inactive'};if(!data.full_name||!data.employee_number||!main){msg('الاسم ورقم الموظف والقسم الرئيسي مطلوبة',true);return}let id=v('employeeId');let r=await fetch(id?`${API_BASE_URL}/employees/${id}`:`${API_BASE_URL}/employees`,{method:id?'PUT':'POST',headers:{Authorization:`Bearer ${token}`,'Content-Type':'application/json'},body:JSON.stringify(data)});let d=await r.json();if(!r.ok){msg(d.error||'تعذر حفظ الموظف',true);return}msg(d.message||'تم حفظ الموظف');resetForm();await loadEmployees()});
async function removeEmployee(id){if(!confirm('هل أنت متأكد من حذف الموظف؟'))return;let r=await fetch(`${API_BASE_URL}/employees/${id}`,{method:'DELETE',headers:{Authorization:`Bearer ${token}`}});let d=await r.json();if(r.status===409){let action=confirm((d.error||'لا يمكن الحذف')+'\nموافق للتعطيل، إلغاء للأرشفة')?'disable':'archive';let rr=await fetch(`${API_BASE_URL}/employees/${id}/${action}`,{method:'PATCH',headers:{Authorization:`Bearer ${token}`}});let dd=await rr.json();msg(dd.message||dd.error,!rr.ok);await loadEmployees();return}msg(d.message||d.error,!r.ok);await loadEmployees()}
bodyEl.addEventListener('click',e=>{let b=e.target.closest('button');if(!b)return;let id=b.dataset.id;if(b.dataset.a==='view')location.href=`./employee-profile.html?id=${id}`;if(b.dataset.a==='edit')editEmployee(id);if(b.dataset.a==='del')removeEmployee(id)});
mainDepSel.addEventListener('change',()=>renderSubDepartments());document.getElementById('cancelEditBtn').addEventListener('click',resetForm);q.addEventListener('input',renderEmployees);depFilter.addEventListener('change',renderEmployees);stFilter.addEventListener('change',renderEmployees);document.getElementById('refreshEmployeesBtn').addEventListener('click',loadEmployees);document.getElementById('exportEmployeesBtn').addEventListener('click',()=>msg('تم تجهيز البيانات للتصدير من التقارير'));
initEmployees();
