const tableBody=document.getElementById('requestsTableBody');
const form=document.getElementById('requestForm');
const formMessage=document.getElementById('formMessage');
const employeeSelect=document.getElementById('employee_id');
const searchInput=document.getElementById('requestSearchInput');
const employeeFilter=document.getElementById('requestEmployeeFilter');
const typeFilter=document.getElementById('requestTypeFilter');
const statusFilter=document.getElementById('requestStatusFilter');
const fromDate=document.getElementById('requestFromDate');
const toDate=document.getElementById('requestToDate');
const countText=document.getElementById('requestsCountText');
const cards={total:document.getElementById('requestsTotalCard'),pending:document.getElementById('requestsPendingCard'),info:document.getElementById('requestsInfoCard'),closed:document.getElementById('requestsClosedCard')};
const requestModal=document.getElementById('requestModal');
const detailsModal=document.getElementById('detailsModal');
const actionModal=document.getElementById('actionModal');
const dynamicFields=document.getElementById('dynamicRequestFields');
const actionTitle=document.getElementById('actionModalTitle');
const actionHelp=document.getElementById('actionModalHelp');
const actionNote=document.getElementById('actionNoteInput');
const actionMessage=document.getElementById('actionModalMessage');
const confirmActionBtn=document.getElementById('confirmActionBtn');
let requests=[];let employees=[];let selectedType='leave';let activeAction=null;let selectedDetails=null;let filterTimer=null;let detailsCache=new Map();let detailsAbort=null;
const typeLabels={leave:'طلب إجازة',exit:'طلب مغادرة',advance:'طلب سلفة',resignation:'طلب استقالة',complaint:'شكوى',custom:'طلب مخصص'};
const statusLabels={draft:'مسودة',pending:'قيد الانتظار',needs_info:'يحتاج معلومات',approved:'موافق عليه',rejected:'مرفوض',cancelled:'ملغي'};
const statusClasses={draft:'inactive-badge',pending:'warning-badge',needs_info:'primary-badge',approved:'active-badge',rejected:'absence-unexcused-badge',cancelled:'inactive-badge'};
const actionLabels={created:'تم إنشاء الطلب',submitted:'تم إرسال الطلب',updated:'تم التعديل',approve:'تمت الموافقة',reject:'تم الرفض',cancel:'تم الإلغاء',request_info:'طلب معلومات',respond_info:'الرد على طلب المعلومات',comment:'تعليق'};
const actionModalConfig={approve:{title:'تأكيد الموافقة',help:'يمكنك إضافة ملاحظة اختيارية، أو ترك الحقل فارغًا.',placeholder:'ملاحظة اختيارية',button:'موافقة'},reject:{title:'تأكيد الرفض',help:'سبب الرفض اختياري في هذه المرحلة.',placeholder:'سبب الرفض، اختياري',button:'رفض'},cancel:{title:'تأكيد الإلغاء',help:'يمكنك كتابة سبب الإلغاء إن وجد.',placeholder:'سبب الإلغاء، اختياري',button:'إلغاء الطلب'},request_info:{title:'طلب معلومات',help:'اكتب المعلومات المطلوبة من الموظف.',placeholder:'ما المعلومات المطلوبة؟',button:'إرسال الطلب'},respond_info:{title:'الرد على طلب المعلومات',help:'اكتب ردك على طلب المعلومات.',placeholder:'اكتب ردك',button:'إرسال الرد'},comment:{title:'إضافة تعليق',help:'اكتب التعليق المطلوب.',placeholder:'تعليق',button:'إضافة تعليق'}};
function msg(t,b=false){formMessage.textContent=t;formMessage.className='inline-message '+(b?'error-message':'success-message')}
function actionMsg(t,b=false){actionMessage.textContent=t;actionMessage.className='inline-message '+(b?'error-message':'success-message')}
function v(id){return(document.getElementById(id)?.value||'').trim()}
function sv(id,x){let e=document.getElementById(id);if(e)e.value=x??''}
function fmt(d){return d?String(d).replace('T',' ').slice(0,16):'-'}
function dayFmt(d){return d?String(d).split('T')[0]:'-'}
function days(s,e){if(!s||!e)return 0;let n=Math.round((new Date(e)-new Date(s))/86400000)+1;return n>0?n:0}
function setButtonLoading(btn,on,text){if(!btn)return;if(on){btn.dataset.oldText=btn.textContent;btn.textContent='جارٍ التنفيذ';btn.disabled=true;btn.classList.add('button-loading')}else{btn.textContent=btn.dataset.oldText||text||btn.textContent;btn.disabled=false;btn.classList.remove('button-loading')}}
async function fetchJson(url,opt={}){let r=await fetch(url,{headers:{Authorization:`Bearer ${token}`,'Content-Type':'application/json'},...opt});let d=await r.json().catch(()=>({}));if(!r.ok)throw new Error(d.error||'فشل الطلب');return d}
async function initRequests(){let user=await loadLoggedUser();if(!user)return;fillFilters();renderModalFields('leave');await Promise.all([loadEmployees(),loadRequests()]);}
function fillFilters(){typeFilter.innerHTML='<option value="">كل أنواع الطلبات</option>'+Object.entries(typeLabels).map(([k,l])=>`<option value="${k}">${l}</option>`).join('');statusFilter.innerHTML='<option value="">كل الحالات</option>'+Object.entries(statusLabels).map(([k,l])=>`<option value="${k}">${l}</option>`).join('')}
async function loadEmployees(){try{let d=await fetchJson(`${API_BASE_URL}/employees`);employees=d.employees||[];employeeSelect.innerHTML='<option value="">موظفي الحالي</option>';employeeFilter.innerHTML='<option value="">كل الموظفين</option>';employees.forEach(e=>{let label=`${e.full_name} - ${e.employee_number||e.id}`;employeeSelect.innerHTML+=`<option value="${e.id}">${label}</option>`;employeeFilter.innerHTML+=`<option value="${e.id}">${label}</option>`})}catch(e){employeeSelect.innerHTML='<option value="">الموظف الحالي</option>';employeeFilter.innerHTML='<option value="">كل الموظفين</option>'}}
async function loadRequests(){try{countText.textContent='جاري تحميل البيانات...';let d=await fetchJson(`${API_BASE_URL}/leaves`);requests=d.requests||[];renderRequests()}catch(e){requests=[];setCards([]);countText.textContent='تعذر تحميل البيانات';tableBody.innerHTML=`<tr><td colspan="9">${e.message||'حدث خطأ أثناء تحميل البيانات'}</td></tr>`}}
function setCards(list){cards.total.textContent=list.length;cards.pending.textContent=list.filter(x=>x.status==='pending').length;cards.info.textContent=list.filter(x=>x.status==='needs_info').length;cards.closed.textContent=list.filter(x=>['approved','rejected','cancelled'].includes(x.status)).length}
function filtered(){let q=searchInput.value.trim().toLowerCase(),emp=employeeFilter.value,tp=typeFilter.value,st=statusFilter.value,from=fromDate.value,to=toDate.value;return requests.filter(r=>{let data=r.request_data||{};let text=[r.employee_name,r.employee_number,r.department_name,r.request_title,data.reason,data.title,data.details].filter(Boolean).join(' ').toLowerCase();let d=dayFmt(r.created_at);return(!q||text.includes(q))&&(!emp||String(r.employee_id)===emp)&&(!tp||r.request_type===tp)&&(!st||r.status===st)&&(!from||d>=from)&&(!to||d<=to)})}
function renderRequests(){let list=filtered();setCards(list);countText.textContent=`عرض ${list.length} من أصل ${requests.length} طلب`;if(!list.length){tableBody.innerHTML='<tr><td colspan="9">لا توجد طلبات مطابقة</td></tr>';return}tableBody.innerHTML=list.map(r=>`<tr><td>${r.id}</td><td>${r.employee_name||'-'}</td><td>${r.employee_number||'-'}</td><td>${r.department_name||'-'}</td><td>${typeLabels[r.request_type]||'-'}</td><td>${r.request_title||'-'}</td><td><span class="status-badge ${statusClasses[r.status]||'info-badge'}">${statusLabels[r.status]||r.status}</span></td><td>${fmt(r.updated_at||r.created_at)}</td><td><div class="row-actions"><button class="secondary-btn small-btn" data-a="details" data-id="${r.id}">عرض التفاصيل</button></div></td></tr>`).join('')}
function openModal(modal){modal.classList.add('is-open');modal.setAttribute('aria-hidden','false');document.body.classList.add('no-scroll')}
function closeModal(modal){modal.classList.remove('is-open');modal.setAttribute('aria-hidden','true');document.body.classList.remove('no-scroll')}
function renderModalFields(type){selectedType=type;sv('request_type',type);document.getElementById('requestFormTitle').textContent=typeLabels[type]||'إنشاء طلب';let html='';if(type==='leave')html=`<select id="leave_type"><option value="annual">سنوية</option><option value="sick">مرضية</option><option value="emergency">طارئة</option><option value="unpaid">بدون راتب</option><option value="other">أخرى</option></select><input type="date" id="start_date"/><input type="date" id="end_date"/><input type="number" id="days_preview" placeholder="عدد الأيام" readonly/><input class="full-width" type="text" id="reason" placeholder="سبب الإجازة"/><textarea class="full-width" id="details" placeholder="ملاحظات اختيارية"></textarea>`;
if(type==='exit')html=`<input type="date" id="exit_date"/><input type="time" id="exit_time"/><input type="time" id="return_time"/><input class="full-width" type="text" id="reason" placeholder="سبب المغادرة"/><textarea class="full-width" id="details" placeholder="ملاحظات اختيارية"></textarea>`;
if(type==='advance')html=`<input type="number" id="advance_amount" placeholder="المبلغ المطلوب" min="0" step="0.01"/><input type="text" id="deduction_method" placeholder="طريقة الخصم المقترحة"/><input class="full-width" type="text" id="reason" placeholder="سبب السلفة"/><textarea class="full-width" id="details" placeholder="ملاحظات اختيارية"></textarea>`;
if(type==='resignation')html=`<input type="date" id="last_working_day"/><input type="text" id="reason" placeholder="سبب الاستقالة"/><input class="full-width" type="text" id="handover_notes" placeholder="ملاحظات تسليم العهدة"/><textarea class="full-width" id="details" placeholder="ملاحظات اختيارية"></textarea>`;
if(type==='complaint')html=`<input type="text" id="complaint_title" placeholder="عنوان الشكوى"/><select id="is_confidential"><option value="false">غير سرية</option><option value="true">سرية</option></select><input class="full-width" type="text" id="against_employee" placeholder="ضد موظف، اختياري"/><textarea class="full-width" id="details" placeholder="تفاصيل الشكوى"></textarea><input class="full-width" type="text" id="reason" placeholder="ملاحظات اختيارية"/>`;
if(type==='custom')html=`<input class="full-width" type="text" id="custom_title" placeholder="عنوان الطلب"/><textarea class="full-width" id="details" placeholder="تفاصيل الطلب"></textarea><input class="full-width" type="text" id="reason" placeholder="ملاحظات اختيارية"/>`;
dynamicFields.innerHTML=html;['start_date','end_date'].forEach(id=>{let el=document.getElementById(id);if(el)el.addEventListener('change',()=>sv('days_preview',days(v('start_date'),v('end_date'))||''))})}
function openRequestForm(type){form.reset();renderModalFields(type);sv('request_type',type);openModal(requestModal)}
function buildData(){let common={reason:v('reason'),notes:v('details')};if(selectedType==='leave')return{...common,leave_type:v('leave_type'),start_date:v('start_date'),end_date:v('end_date'),days_count:days(v('start_date'),v('end_date'))};if(selectedType==='exit')return{...common,exit_date:v('exit_date'),exit_time:v('exit_time'),return_time:v('return_time')};if(selectedType==='advance')return{...common,amount:Number(v('advance_amount')||0),deduction_method:v('deduction_method')};if(selectedType==='resignation')return{...common,last_working_day:v('last_working_day'),handover_notes:v('handover_notes')};if(selectedType==='complaint')return{title:v('complaint_title'),details:v('details'),against_employee:v('against_employee'),is_confidential:v('is_confidential')==='true',notes:v('reason')};if(selectedType==='custom')return{title:v('custom_title'),details:v('details'),notes:v('reason')};return common}
async function submitRequest(status='pending',btn=null){try{setButtonLoading(btn,true);let data=buildData();let body={employee_id:v('employee_id')||null,request_type:selectedType,request_data:data,status};let d=await fetchJson(`${API_BASE_URL}/leaves`,{method:'POST',body:JSON.stringify(body)});requests=[d.request,...requests];detailsCache.set(String(d.request.id),{request:d.request,logs:[]});renderRequests();closeModal(requestModal);msg(d.message||'تم إرسال الطلب بنجاح');form.reset()}catch(e){msg(e.message||'حدث خطأ أثناء إرسال الطلب',true)}finally{setButtonLoading(btn,false)}}
function renderDetailsSkeleton(id){sv('selectedRequestId',id);document.getElementById('requestDetailsSubtitle').textContent='جاري تحميل التفاصيل...';document.getElementById('requestDetailsBox').innerHTML='<div class="full-width empty-state">جاري تحميل تفاصيل الطلب...</div>';document.getElementById('requestLogsBody').innerHTML='<tr><td colspan="5">جاري تحميل سجل الإجراءات...</td></tr>'}
async function openDetails(id,btn=null){setButtonLoading(btn,true,'عرض التفاصيل');openModal(detailsModal);renderDetailsSkeleton(id);try{if(detailsCache.has(String(id))){renderDetails(detailsCache.get(String(id)));return}if(detailsAbort)detailsAbort.abort();detailsAbort=new AbortController();let r=await fetch(`${API_BASE_URL}/leaves/${id}`,{headers:{Authorization:`Bearer ${token}`},signal:detailsAbort.signal});let d=await r.json().catch(()=>({}));if(!r.ok)throw new Error(d.error||'تعذر تحميل التفاصيل');detailsCache.set(String(id),d);renderDetails(d)}catch(e){if(e.name!=='AbortError'){document.getElementById('requestDetailsBox').innerHTML=`<div class="full-width empty-state">${e.message||'حدث خطأ أثناء تحميل التفاصيل'}</div>`}}finally{setButtonLoading(btn,false,'عرض التفاصيل')}}
function renderDetails(d){selectedDetails=d.request;let r=d.request,logs=d.logs||[];sv('selectedRequestId',r.id);document.getElementById('requestDetailsSubtitle').textContent=`${typeLabels[r.request_type]} - ${statusLabels[r.status]}`;let data=r.request_data||{};document.getElementById('requestDetailsBox').innerHTML=`<div><strong>الموظف:</strong> ${r.employee_name||'-'}</div><div><strong>رقم الموظف:</strong> ${r.employee_number||'-'}</div><div><strong>القسم:</strong> ${r.department_name||'-'}</div><div><strong>نوع الطلب:</strong> ${typeLabels[r.request_type]||'-'}</div><div><strong>الحالة:</strong> ${statusLabels[r.status]||'-'}</div><div><strong>تاريخ الإنشاء:</strong> ${fmt(r.created_at)}</div><div class="full-width"><strong>بيانات الطلب:</strong><br>${formatRequestData(r.request_type,data)}</div><div class="full-width"><strong>ملاحظة القرار:</strong> ${r.final_decision_reason||'-'}</div>`;document.getElementById('requestLogsBody').innerHTML=logs.length?logs.map(l=>`<tr><td>${l.id}</td><td>${actionLabels[l.action]||'-'}</td><td>${l.actor_name||'-'}</td><td>${formatLogText(l)}</td><td>${fmt(l.created_at)}</td></tr>`).join(''):'<tr><td colspan="5">لا توجد إجراءات بعد</td></tr>'}
function formatLogText(l){let text=l.comment||l.reason||'';if(!text)return '<span class="timeline-note">-</span>';if(l.action==='approve')return `<span class="timeline-note"><strong>ملاحظة:</strong> ${text}</span>`;if(l.action==='reject')return `<span class="timeline-note"><strong>سبب الرفض:</strong> ${text}</span>`;if(l.action==='cancel')return `<span class="timeline-note"><strong>سبب الإلغاء:</strong> ${text}</span>`;if(l.action==='request_info')return `<span class="timeline-note"><strong>طلب معلومات:</strong> ${text}</span>`;if(l.action==='respond_info')return `<span class="timeline-note"><strong>الرد على طلب المعلومات:</strong> ${text}</span>`;if(l.action==='comment')return `<span class="timeline-note"><strong>تعليق:</strong> ${text}</span>`;return `<span class="timeline-note">${text}</span>`}
function formatRequestData(type,data){if(type==='leave')return`نوع الإجازة: ${data.leave_type||'-'}<br>من: ${data.start_date||'-'}<br>إلى: ${data.end_date||'-'}<br>عدد الأيام: ${data.days_count||'-'}<br>السبب: ${data.reason||'-'}<br>ملاحظات: ${data.notes||'-'}`;if(type==='exit')return`التاريخ: ${data.exit_date||'-'}<br>وقت المغادرة: ${data.exit_time||'-'}<br>وقت العودة المتوقع: ${data.return_time||'-'}<br>السبب: ${data.reason||'-'}<br>ملاحظات: ${data.notes||'-'}`;if(type==='advance')return`المبلغ: ${data.amount||'-'}<br>سبب السلفة: ${data.reason||'-'}<br>طريقة الخصم: ${data.deduction_method||'-'}<br>ملاحظات: ${data.notes||'-'}`;if(type==='resignation')return`آخر يوم عمل: ${data.last_working_day||'-'}<br>سبب الاستقالة: ${data.reason||'-'}<br>العهدة: ${data.handover_notes||'-'}<br>ملاحظات: ${data.notes||'-'}`;if(type==='complaint')return`العنوان: ${data.title||'-'}<br>التفاصيل: ${data.details||'-'}<br>ضد موظف: ${data.against_employee||'-'}<br>السرية: ${data.is_confidential?'نعم':'لا'}`;return`العنوان: ${data.title||'-'}<br>التفاصيل: ${data.details||'-'}<br>ملاحظات: ${data.notes||'-'}`}
function openActionModal(action,btn){activeAction=action;let cfg=actionModalConfig[action];actionTitle.textContent=cfg.title;actionHelp.textContent=cfg.help;actionNote.placeholder=cfg.placeholder;confirmActionBtn.textContent=cfg.button;actionNote.value='';actionMsg('');openModal(actionModal);setTimeout(()=>actionNote.focus(),50)}
async function confirmAction(){let id=v('selectedRequestId');if(!id)return actionMsg('اختر طلبًا أولاً',true);let note=actionNote.value.trim();if(activeAction==='request_info'&&!note)return actionMsg('يرجى كتابة المعلومات المطلوبة',true);if(activeAction==='respond_info'&&!note)return actionMsg('يرجى كتابة الرد',true);if(activeAction==='comment'&&!note)return actionMsg('يجب إدخال تعليق',true);try{setButtonLoading(confirmActionBtn,true);let d=await fetchJson(`${API_BASE_URL}/leaves/${id}/action`,{method:'PATCH',body:JSON.stringify({action:activeAction,note,comment:note,reason:note})});requests=requests.map(r=>String(r.id)===String(id)?{...r,...d.request}:r);detailsCache.delete(String(id));renderRequests();closeModal(actionModal);await openDetails(id);msg(d.message||'تم تنفيذ الإجراء بنجاح')}catch(e){actionMsg(e.message,true)}finally{setButtonLoading(confirmActionBtn,false)}}
function exportCSV(){let rows=[['id','employee','number','department','type','title','status','updated'],...filtered().map(r=>[r.id,r.employee_name,r.employee_number,r.department_name,typeLabels[r.request_type],r.request_title,statusLabels[r.status],fmt(r.updated_at)])];let csv=rows.map(row=>row.map(x=>`"${String(x??'').replace(/"/g,'""')}"`).join(',')).join('\n');let blob=new Blob(['\uFEFF'+csv],{type:'text/csv;charset=utf-8;'});let url=URL.createObjectURL(blob);let a=document.createElement('a');a.href=url;a.download='requests.csv';a.click();URL.revokeObjectURL(url)}
document.querySelectorAll('.request-type-card').forEach(btn=>btn.addEventListener('click',()=>openRequestForm(btn.dataset.type)));
document.getElementById('submitRequestBtn').addEventListener('click',e=>{e.preventDefault();submitRequest('pending',e.currentTarget)});
document.getElementById('saveDraftBtn').addEventListener('click',e=>{e.preventDefault();submitRequest('draft',e.currentTarget)});
document.getElementById('resetRequestBtn').addEventListener('click',()=>closeModal(requestModal));document.getElementById('closeRequestModalBtn').addEventListener('click',()=>closeModal(requestModal));
tableBody.addEventListener('click',e=>{let b=e.target.closest('button');if(b&&b.dataset.a==='details')openDetails(b.dataset.id,b)});
document.getElementById('closeDetailsBtn').addEventListener('click',()=>closeModal(detailsModal));
document.getElementById('approveRequestBtn').addEventListener('click',e=>openActionModal('approve',e.currentTarget));
document.getElementById('rejectRequestBtn').addEventListener('click',e=>openActionModal('reject',e.currentTarget));
document.getElementById('requestInfoBtn').addEventListener('click',e=>openActionModal('request_info',e.currentTarget));
document.getElementById('respondInfoBtn').addEventListener('click',e=>openActionModal('respond_info',e.currentTarget));
document.getElementById('cancelRequestBtn').addEventListener('click',e=>openActionModal('cancel',e.currentTarget));
document.getElementById('confirmActionBtn').addEventListener('click',confirmAction);document.getElementById('closeActionModalBtn').addEventListener('click',()=>closeModal(actionModal));document.getElementById('cancelActionModalBtn').addEventListener('click',()=>closeModal(actionModal));
[requestModal,detailsModal,actionModal].forEach(m=>m.addEventListener('click',e=>{if(e.target===m)closeModal(m)}));
[searchInput,employeeFilter,typeFilter,statusFilter,fromDate,toDate].forEach(el=>{el.addEventListener('input',()=>{clearTimeout(filterTimer);filterTimer=setTimeout(renderRequests,120)});el.addEventListener('change',renderRequests)});
document.getElementById('refreshRequestsBtn').addEventListener('click',loadRequests);document.getElementById('exportRequestsBtn').addEventListener('click',exportCSV);
initRequests();
