const tableBody=document.getElementById('leavesTableBody');
const form=document.getElementById('leaveForm');
const formMessage=document.getElementById('formMessage');
const employeeSelect=document.getElementById('employee_id');
const searchInput=document.getElementById('leaveSearchInput');
const employeeFilter=document.getElementById('leaveEmployeeFilter');
const mainDepFilter=document.getElementById('leaveMainDepartmentFilter');
const subDepFilter=document.getElementById('leaveSubDepartmentFilter');
const statusFilter=document.getElementById('leaveStatusFilter');
const typeFilter=document.getElementById('leaveTypeFilter');
const monthFilter=document.getElementById('leaveMonthFilter');
const fromDate=document.getElementById('leaveFromDate');
const toDate=document.getElementById('leaveToDate');
const refreshBtn=document.getElementById('refreshLeavesBtn');
const exportBtn=document.getElementById('exportLeavesBtn');
const countText=document.getElementById('leavesCountText');
const cards={total:document.getElementById('leavesTotalCard'),pending:document.getElementById('leavesPendingCard'),approved:document.getElementById('leavesApprovedCard'),rejected:document.getElementById('leavesRejectedCard')};
let leaves=[];let employees=[];
const typeLabels={annual:'سنوية',sick:'مرضية',unpaid:'بدون راتب',emergency:'طارئة',other:'أخرى'};
const statusLabels={pending:'قيد الانتظار',approved:'مقبولة',rejected:'مرفوضة',cancelled:'ملغاة'};
const statusClasses={pending:'warning-badge',approved:'active-badge',rejected:'inactive-badge',cancelled:'info-badge'};
function msg(t,b){formMessage.textContent=t;formMessage.className='inline-message '+(b?'error-message':'success-message')}
function val(id){return(document.getElementById(id)?.value||'').trim()}
function setVal(id,v){let e=document.getElementById(id);if(e)e.value=v??''}
function fmt(d){return d?String(d).split('T')[0]:'-'}
function days(s,e){if(!s||!e)return 0;let n=Math.round((new Date(e)-new Date(s))/86400000)+1;return n>0?n:0}
function setCards(list=[]){cards.total.textContent=list.length;cards.pending.textContent=list.filter(x=>x.status==='pending').length;cards.approved.textContent=list.filter(x=>x.status==='approved').length;cards.rejected.textContent=list.filter(x=>x.status==='rejected'||x.status==='cancelled').length}
async function initLeaves(){let u=await loadLoggedUser();if(!u||u.role==='employee'){location.href='./dashboard.html';return}setEmptyLoading();await loadEmployees();await loadLeaves();updateDaysPreview()}
function setEmptyLoading(){if(countText)countText.textContent='جاري تحميل البيانات...';if(tableBody)tableBody.innerHTML='<tr><td colspan="12">جاري تحميل البيانات...</td></tr>'}
async function loadEmployees(){try{let r=await fetch(`${API_BASE_URL}/employees`,{headers:{Authorization:`Bearer ${token}`}});let d=await r.json();if(!r.ok)throw new Error(d.error||'تعذر تحميل الموظفين');employees=d.employees||[];employeeSelect.innerHTML='<option value="">اختر الموظف</option>';employeeFilter.innerHTML='<option value="">كل الموظفين</option>';employees.forEach(e=>{let label=`${e.full_name} - ${e.primary_department?.department_name||e.department_name||'بدون قسم'}`;employeeSelect.innerHTML+=`<option value="${e.id}">${label}</option>`;employeeFilter.innerHTML+=`<option value="${e.id}">${label}</option>`});renderDepartmentFilters()}catch(error){employees=[];employeeSelect.innerHTML='<option value="">تعذر تحميل الموظفين</option>';employeeFilter.innerHTML='<option value="">تعذر تحميل الموظفين</option>';mainDepFilter.innerHTML='<option value="">كل الأقسام الرئيسية</option>';subDepFilter.innerHTML='<option value="">كل الأقسام الفرعية</option>';msg(error.message||'تعذر تحميل قائمة الموظفين',true)}}
function renderDepartmentFilters(){let main=new Map(),sub=new Map();employees.forEach(e=>{if(e.primary_department)main.set(String(e.primary_department.department_id),e.primary_department.department_name);else if(e.department_id&&e.department_name)main.set(String(e.department_id),e.department_name);(e.additional_departments||[]).forEach(x=>sub.set(String(x.department_id),x.department_name))});mainDepFilter.innerHTML='<option value="">كل الأقسام الرئيسية</option>'+Array.from(main).map(([id,name])=>`<option value="${id}">${name}</option>`).join('');subDepFilter.innerHTML='<option value="">كل الأقسام الفرعية</option>'+Array.from(sub).map(([id,name])=>`<option value="${id}">${name}</option>`).join('')}
async function loadLeaves(){try{countText.textContent='جاري تحميل البيانات...';tableBody.innerHTML='<tr><td colspan="12">جاري تحميل البيانات...</td></tr>';let r=await fetch(`${API_BASE_URL}/leaves`,{headers:{Authorization:`Bearer ${token}`}});let d=await r.json();if(!r.ok)throw new Error(d.error||'تعذر تحميل طلبات الإجازة');leaves=d.leaves||[];renderLeaves()}catch(error){leaves=[];setCards([]);tableBody.innerHTML=`<tr><td colspan="12">${error.message||'تعذر تحميل البيانات'}</td></tr>`;countText.textContent='تعذر تحميل البيانات';msg(error.message||'تعذر تحميل طلبات الإجازة',true)}}
function filtered(){let q=searchInput.value.trim().toLowerCase(),emp=employeeFilter.value,main=mainDepFilter.value,sub=subDepFilter.value,st=statusFilter.value,tp=typeFilter.value,month=monthFilter.value,from=fromDate.value,to=toDate.value;return leaves.filter(l=>{let start=fmt(l.start_date),end=fmt(l.end_date);let text=[l.employee_name,l.reason,l.admin_notes,l.decision_reason,l.primary_department_name,l.sub_department_name].filter(Boolean).join(' ').toLowerCase();return(!q||text.includes(q))&&(!emp||String(l.employee_id)===emp)&&(!main||String(l.primary_department_id)===main)&&(!sub||String(l.sub_department_id)===sub)&&(!st||l.status===st)&&(!tp||l.leave_type===tp)&&(!month||start.startsWith(month)||end.startsWith(month))&&(!from||end>=from)&&(!to||start<=to)})}
function renderLeaves(){let list=filtered();countText.textContent=`عرض ${list.length} من أصل ${leaves.length} طلب`;setCards(list);if(!list.length){tableBody.innerHTML='<tr><td colspan="12">لا توجد طلبات مطابقة</td></tr>';return}tableBody.innerHTML='';list.forEach(l=>{let tr=document.createElement('tr');tr.innerHTML=`<td>${l.id}</td><td>${l.employee_name||'-'}</td><td>${l.primary_department_name||'-'}</td><td>${l.sub_department_name||'-'}</td><td>${typeLabels[l.leave_type]||l.leave_type}</td><td>${fmt(l.start_date)}</td><td>${fmt(l.end_date)}</td><td>${l.days_count||days(l.start_date,l.end_date)}</td><td>${l.reason||'-'}</td><td><span class="status-badge ${statusClasses[l.status]||'info-badge'}">${statusLabels[l.status]||l.status}</span></td><td>${l.decision_reason||l.admin_notes||'-'}</td><td><div class="row-actions"><button class="secondary-btn small-btn" data-a="view" data-id="${l.employee_id}">الملف</button><button class="edit-btn small-btn" data-a="edit" data-id="${l.id}">تعديل</button>${l.status==='pending'?`<button class="secondary-btn small-btn" data-a="approve" data-id="${l.id}">قبول</button><button class="danger-btn small-btn" data-a="reject" data-id="${l.id}">رفض</button>`:''}<button class="secondary-btn small-btn" data-a="cancel" data-id="${l.id}">إلغاء</button><button class="danger-btn small-btn" data-a="delete" data-id="${l.id}">حذف</button></div></td>`;tableBody.appendChild(tr)})}
function updateDaysPreview(){setVal('days_preview',days(val('start_date'),val('end_date'))||'')}
function resetForm(){form.reset();setVal('leaveId','');document.getElementById('leaveFormTitle').textContent='طلب إجازة';updateDaysPreview()}
function editLeave(id){let l=leaves.find(x=>String(x.id)===String(id));if(!l)return;setVal('leaveId',l.id);setVal('employee_id',l.employee_id);setVal('leave_type',l.leave_type);setVal('start_date',fmt(l.start_date));setVal('end_date',fmt(l.end_date));setVal('reason',l.reason);setVal('admin_notes',l.admin_notes);updateDaysPreview();document.getElementById('leaveFormTitle').textContent='تعديل طلب إجازة';scrollTo({top:0,behavior:'smooth'})}
form.addEventListener('submit',async e=>{e.preventDefault();let body={employee_id:employeeSelect.value,leave_type:val('leave_type'),start_date:val('start_date'),end_date:val('end_date'),reason:val('reason'),admin_notes:val('admin_notes')};if(!body.employee_id||!body.start_date||!body.end_date){msg('الموظف وتاريخ البداية والنهاية مطلوبة',true);return}if(days(body.start_date,body.end_date)<=0){msg('تاريخ نهاية الإجازة يجب أن يكون بعد تاريخ البداية',true);return}let id=val('leaveId');let r=await fetch(id?`${API_BASE_URL}/leaves/${id}`:`${API_BASE_URL}/leaves`,{method:id?'PUT':'POST',headers:{Authorization:`Bearer ${token}`,'Content-Type':'application/json'},body:JSON.stringify(body)});let d=await r.json();if(!r.ok){msg(d.error||'تعذر حفظ الطلب',true);return}msg(d.message||'تم حفظ الطلب');resetForm();await loadLeaves()});
async function changeStatus(id,status){let reason='';if(status==='rejected'||status==='cancelled'){reason=prompt(status==='rejected'?'اكتب سبب الرفض':'اكتب سبب الإلغاء')||'';if(!reason.trim()){msg('سبب القرار مطلوب',true);return}}let r=await fetch(`${API_BASE_URL}/leaves/${id}`,{method:'PATCH',headers:{Authorization:`Bearer ${token}`,'Content-Type':'application/json'},body:JSON.stringify({status,decision_reason:reason,admin_notes:reason})});let d=await r.json();msg(d.message||d.error,!r.ok);await loadLeaves()}
async function deleteLeave(id){if(!confirm('هل أنت متأكد من حذف طلب الإجازة؟'))return;let r=await fetch(`${API_BASE_URL}/leaves/${id}`,{method:'DELETE',headers:{Authorization:`Bearer ${token}`}});let d=await r.json();msg(d.message||d.error,!r.ok);await loadLeaves()}
tableBody.addEventListener('click',e=>{let b=e.target.closest('button');if(!b)return;let id=b.dataset.id;if(b.dataset.a==='view')location.href=`./employee-profile.html?id=${id}`;if(b.dataset.a==='edit')editLeave(id);if(b.dataset.a==='approve')changeStatus(id,'approved');if(b.dataset.a==='reject')changeStatus(id,'rejected');if(b.dataset.a==='cancel')changeStatus(id,'cancelled');if(b.dataset.a==='delete')deleteLeave(id)});
function exportCSV(){let rows=[['id','employee','main_department','sub_department','type','start','end','days','reason','status','decision'],...filtered().map(l=>[l.id,l.employee_name,l.primary_department_name||'',l.sub_department_name||'',typeLabels[l.leave_type]||l.leave_type,fmt(l.start_date),fmt(l.end_date),l.days_count||days(l.start_date,l.end_date),l.reason||'',statusLabels[l.status]||l.status,l.decision_reason||l.admin_notes||''])];let csv=rows.map(row=>row.map(v=>`"${String(v??'').replace(/"/g,'""')}"`).join(',')).join('\n');let blob=new Blob(['\uFEFF'+csv],{type:'text/csv;charset=utf-8;'});let url=URL.createObjectURL(blob);let a=document.createElement('a');a.href=url;a.download='leaves.csv';a.click();URL.revokeObjectURL(url)}
['start_date','end_date'].forEach(id=>document.getElementById(id).addEventListener('change',updateDaysPreview));document.getElementById('cancelLeaveEditBtn').addEventListener('click',resetForm);[searchInput,employeeFilter,mainDepFilter,subDepFilter,statusFilter,typeFilter,monthFilter,fromDate,toDate].forEach(el=>{el.addEventListener('input',renderLeaves);el.addEventListener('change',renderLeaves)});refreshBtn.addEventListener('click',async()=>{await loadEmployees();await loadLeaves()});exportBtn.addEventListener('click',exportCSV);
initLeaves();
