const el=(id)=>document.getElementById(id);
const money=(v)=>Number(v||0).toFixed(2);
const value=(id)=>String(el(id)?.value||'').trim();
const setValue=(id,v)=>{const node=el(id);if(node)node.value=v??''};
const setText=(id,v)=>{const node=el(id);if(node)node.textContent=v??''};
const msg=(id,text,bad=false)=>{const node=el(id);if(!node)return;node.textContent=text;node.className='inline-message '+(bad?'error-message':'success-message')};
const badge=(text,cls='')=>`<span class="mini-badge ${cls}">${text}</span>`;
const detail=(label,val)=>`<div class="detail-item"><span class="detail-label">${label}</span><span class="detail-value">${val??'-'}</span></div>`;
const fmt=(d)=>d?String(d).replace('T',' ').slice(0,16):'-';
const statusLabels={draft:'مسودة',pending_approval:'بانتظار الاعتماد',approved:'معتمد',paid:'مدفوع',closed:'مغلق',review:'بانتظار الاعتماد',published:'مدفوع'};
const statusClasses={draft:'info-badge',pending_approval:'warning-badge',approved:'active-badge',paid:'primary-badge',closed:'inactive-badge'};
let employees=[],departments=[],salaries=[],settings=[],advances=[],overview=null,currentPreview=null,currentSalaryId=null,currentItems=[],editingItemId=null;
async function fetchJson(url,opt={}){const r=await fetch(url,{...opt,headers:{Authorization:`Bearer ${token}`,'Content-Type':'application/json',...(opt.headers||{})}});const d=await r.json().catch(()=>({}));if(!r.ok)throw new Error(d.error||'فشل الطلب');return d}
async function initFinance(){const user=await loadLoggedUser();if(!user||(!hasAnyPermission(['salaries.view'])&&!hasAnyPermission(['salaries.create']))){location.href='./dashboard.html';return}initMonths();bindEvents();await Promise.all([loadDepartments(),loadEmployees()]);await loadFinanceData();openHashTab()}
function initMonths(){const now=new Date();const month=now.getMonth()+1;const year=now.getFullYear();el('salaryMonthSelect').innerHTML=Array.from({length:12},(_,i)=>`<option value="${String(i+1).padStart(2,'0')}" ${i+1===month?'selected':''}>${i+1}</option>`).join('');setValue('salaryYearInput',year);setValue('advanceStartMonth',`${year}-${String(month).padStart(2,'0')}`);setValue('advancePaidAt',now.toISOString().slice(0,10))}
async function loadDepartments(){try{const d=await fetchJson(`${API_BASE_URL}/departments`);departments=d.departments||[];renderDepartments()}catch(e){departments=[]}}
async function loadEmployees(){try{const d=await fetchJson(`${API_BASE_URL}/employees?limit=500`);employees=d.employees||[];renderEmployeeOptions()}catch(e){employees=[]}}
async function loadFinanceData(){await Promise.all([loadOverview(),loadSettings(),loadSalaries(),loadAdvances()]);renderAll()}
async function loadOverview(){try{overview=(await fetchJson(`${API_BASE_URL}/salaries/finance`)).overview||{}}catch(e){overview={}}}
async function loadSettings(){try{settings=(await fetchJson(`${API_BASE_URL}/salaries/settings`)).settings||[]}catch(e){settings=[]}}
async function loadSalaries(){try{salaries=(await fetchJson(`${API_BASE_URL}/salaries`)).salaries||[]}catch(e){salaries=[]}}
async function loadAdvances(){try{advances=(await fetchJson(`${API_BASE_URL}/salaries/advances`)).advances||[]}catch(e){advances=[]}}
function renderAll(){renderSummary();renderOverview();renderSettingsTable();renderSalariesTable();renderApprovalTable();renderPaymentsTable();renderAdvancesTable();renderReports();renderSalaryRecordOptions()}
function renderDepartments(){const opts='<option value="">كل الأقسام</option>'+departments.map(d=>`<option value="${d.id}">${d.parent_name?d.parent_name+' / ':''}${d.name}</option>`).join('');['settingDepartment','salaryDepartment'].forEach(id=>{if(el(id))el(id).innerHTML=opts})}
function employeeLabel(e){return `${e.full_name} - ${e.employee_number||e.id}`}
function employeeDepartmentId(e){return String(e.department_id||e.primary_department?.department_id||'')}
function renderEmployeeOptions(){const opts='<option value="">اختر الموظف</option>'+employees.map(e=>`<option value="${e.id}" data-department="${employeeDepartmentId(e)}">${employeeLabel(e)}</option>`).join('');['settingEmployee','salaryEmployee','advanceEmployee'].forEach(id=>{if(el(id))el(id).innerHTML=opts})}
function filterEmployeeSelect(selectId,departmentId){const select=el(selectId);Array.from(select.options).forEach(opt=>{if(!opt.value)return;opt.hidden=departmentId&&opt.dataset.department!==String(departmentId)});select.value=''}
function renderSummary(){const salaryRows=overview?.salaries||[];const count=(st)=>salaryRows.find(s=>s.status===st)?.count||salaries.filter(s=>normalizeStatus(s.status)===st).length;setText('draftSalaryCard',count('draft'));setText('pendingSalaryCard',count('pending_approval'));setText('approvedSalaryCard',count('approved'));setText('paidSalaryCard',count('paid'))}
function normalizeStatus(st){if(st==='review')return'pending_approval';if(st==='published')return'paid';return st||'draft'}
function renderOverview(){const salaryTotal=(overview?.salaries||[]).reduce((s,x)=>s+Number(x.total||0),0);const advanceTotal=(overview?.advances||[]).reduce((s,x)=>s+Number(x.total||0),0);el('financeOverviewBox').innerHTML=[detail('إجمالي صافي الرواتب',money(salaryTotal)),detail('إجمالي السلف',money(advanceTotal)),detail('موظفون لديهم إعدادات مالية',overview?.settings?.configured_employees||settings.length),detail('عدد كشوف الرواتب',salaries.length)].join('')}
function renderSettingsTable(){setText('settingsCountText',`عرض ${settings.length} إعداد`);const body=el('settingsTableBody');if(!settings.length){body.innerHTML='<tr><td colspan="9">لا توجد إعدادات محفوظة بعد</td></tr>';return}body.innerHTML=settings.map(s=>`<tr><td>${s.employee_name}<small>${s.employee_number||''}</small></td><td>${s.department_name||'-'}</td><td>${money(s.basic_salary)}</td><td>${money(s.social_security_rate)}%</td><td>دقيقة × ${s.late_minute_multiplier||2}<small>تقريب ${s.late_round_minutes||30} د</small></td><td>يوم × ${s.unexcused_absence_multiplier||2}<small>بعذر من الرصيد</small></td><td>${money(s.remaining_days||0)} / ${money(s.current_balance||0)}</td><td>${fmt(s.updated_at)}</td><td><button class="small-btn secondary-btn" data-edit-setting="${s.employee_id}">تعديل</button></td></tr>`).join('')}
function filteredSalaries(){const q=value('salarySearchInput').toLowerCase(),st=value('salaryStatusFilter'),m=value('salaryMonthFilter');return salaries.filter(s=>{const text=[s.employee_name,s.employee_number,s.salary_month].join(' ').toLowerCase();return(!q||text.includes(q))&&(!st||normalizeStatus(s.status)===st)&&(!m||s.salary_month===m)})}
function renderSalariesTable(){const list=filteredSalaries();setText('salariesCountText',`عرض ${list.length} من أصل ${salaries.length} كشف`);const body=el('salariesTableBody');if(!list.length){body.innerHTML='<tr><td colspan="8">لا توجد كشوف رواتب</td></tr>';return}body.innerHTML=list.map(s=>`<tr><td>${s.id}</td><td>${s.employee_name}<small>${s.employee_number||''}</small></td><td>${s.salary_month}</td><td>${money(s.total_income||s.gross_salary)}</td><td>${money(s.total_deductions)}</td><td>${money(s.net_salary)}</td><td>${badge(statusLabels[normalizeStatus(s.status)]||s.status,statusClasses[normalizeStatus(s.status)]||'info-badge')}</td><td><div class="row-actions"><button class="small-btn secondary-btn" data-view-salary="${s.id}">عرض</button>${actionButtons(s)}</div></td></tr>`).join('')}
function actionButtons(s){const st=normalizeStatus(s.status);let html='';if(st==='draft')html+=`<button class="small-btn edit-btn" data-status-id="${s.id}" data-status="pending_approval">إرسال للاعتماد</button>`;if(st==='pending_approval')html+=`<button class="small-btn edit-btn" data-status-id="${s.id}" data-status="approved">اعتماد</button><button class="small-btn secondary-btn" data-status-id="${s.id}" data-status="draft">إرجاع</button>`;if(st==='approved')html+=`<button class="small-btn secondary-btn" data-status-id="${s.id}" data-status="paid">تسجيل دفع</button>`;if(!['approved','paid','closed'].includes(st))html+=`<button class="small-btn danger-btn" data-delete-salary="${s.id}">حذف</button>`;return html}
function renderApprovalTable(){const list=salaries.filter(s=>normalizeStatus(s.status)==='pending_approval');const body=el('approvalTableBody');if(!list.length){body.innerHTML='<tr><td colspan="5">لا توجد كشوف بانتظار الاعتماد</td></tr>';return}body.innerHTML=list.map(s=>`<tr><td>${s.employee_name}</td><td>${s.salary_month}</td><td>${money(s.net_salary)}</td><td>${badge('بانتظار الاعتماد','warning-badge')}</td><td><div class="row-actions"><button class="small-btn secondary-btn" data-view-salary="${s.id}">مراجعة</button><button class="small-btn edit-btn" data-status-id="${s.id}" data-status="approved">اعتماد</button><button class="small-btn secondary-btn" data-status-id="${s.id}" data-status="draft">إرجاع</button></div></td></tr>`).join('')}
function renderPaymentsTable(){const list=salaries.filter(s=>normalizeStatus(s.status)==='paid');const body=el('paymentsTableBody');if(!list.length){body.innerHTML='<tr><td colspan="5">لا توجد رواتب مدفوعة</td></tr>';return}body.innerHTML=list.map(s=>`<tr><td>${s.employee_name}</td><td>${s.salary_month}</td><td>${money(s.net_salary)}</td><td>${fmt(s.paid_at)}</td><td>${badge('مدفوع','primary-badge')}</td></tr>`).join('')}
function renderAdvancesTable(){setText('advancesCountText',`عرض ${advances.length} سلفة`);const body=el('advancesTableBody');if(!advances.length){body.innerHTML='<tr><td colspan="7">لا توجد سلف</td></tr>';return}body.innerHTML=advances.map(a=>`<tr><td>${a.employee_name}<small>${a.employee_number||''}</small></td><td>${money(a.amount)}</td><td>${a.paid_at||'-'}</td><td>${a.deduction_method==='one_time'?'مرة واحدة':'أقساط'}</td><td>${a.installments_count} × ${money(a.monthly_installment_amount)}</td><td>${a.deduction_start_month||'-'}</td><td>${badge(a.status||'active','status-active')}</td></tr>`).join('')}
function renderReports(){const income=salaries.reduce((sum,s)=>sum+Number(s.total_income||s.gross_salary||0),0),ded=salaries.reduce((sum,s)=>sum+Number(s.total_deductions||0),0),net=salaries.reduce((sum,s)=>sum+Number(s.net_salary||0),0);el('financeReportsBox').innerHTML=[detail('إجمالي الدخل',money(income)),detail('إجمالي الاقتطاعات',money(ded)),detail('صافي الرواتب',money(net)),detail('عدد السلف',advances.length)].join('')}
function renderSalaryRecordOptions(){const opts='<option value="">اختر كشف راتب</option>'+salaries.filter(s=>!['approved','paid','closed'].includes(normalizeStatus(s.status))).map(s=>`<option value="${s.id}">${s.employee_name} - ${s.salary_month} - ${money(s.net_salary)}</option>`).join('');el('itemSalaryRecord').innerHTML=opts}
function collectSetting(){return{employee_id:value('settingEmployee'),basic_salary:Number(value('settingBasicSalary')||0),social_security_rate:Number(value('settingSocialSecurityRate')||7.5),overtime_multiplier:Number(value('settingOvertimeMultiplier')||1.25),holiday_overtime_multiplier:Number(value('settingHolidayMultiplier')||1.5),late_deduction_method:value('settingLateMethod')||'minutes_multiplier',late_minute_multiplier:Number(value('settingLateMinuteMultiplier')||2),late_round_minutes:Number(value('settingLateRoundMinutes')||30),late_round_to_hours:value('settingLateRoundToHours')!=='false',absence_deduction_method:value('settingAbsenceMethod')||'leave_balance_then_salary',unexcused_absence_multiplier:Number(value('settingUnexcusedAbsenceMultiplier')||2),personal_exit_hours_per_leave_day:Number(value('settingExitHoursPerLeaveDay')||8),leave_balance:Number(value('settingLeaveBalance')||0),leave_consumed_days:Number(value('settingLeaveConsumed')||0),salary_cycle_start_day:Number(value('settingCycleStart')||1),salary_cycle_end_day:Number(value('settingCycleEnd')||31),notes:value('settingNotes')||null}}
async function saveSetting(e){e.preventDefault();try{const body=collectSetting();if(!body.employee_id)throw new Error('اختر الموظف');const d=await fetchJson(`${API_BASE_URL}/salaries/settings`,{method:'POST',body:JSON.stringify(body)});msg('settingsMessage',d.message||'تم حفظ الإعدادات');el('financeSettingForm').reset();await loadSettings();renderAll()}catch(err){msg('settingsMessage',err.message,true)}}
function editSetting(employeeId){const s=settings.find(x=>String(x.employee_id)===String(employeeId));if(!s)return;setValue('settingEmployee',s.employee_id);setValue('settingBasicSalary',s.basic_salary);setValue('settingSocialSecurityRate',s.social_security_rate);setValue('settingOvertimeMultiplier',s.overtime_multiplier);setValue('settingHolidayMultiplier',s.holiday_overtime_multiplier);setValue('settingLateMethod',s.late_deduction_method||'minutes_multiplier');setValue('settingLateMinuteMultiplier',s.late_minute_multiplier||2);setValue('settingLateRoundMinutes',s.late_round_minutes||30);setValue('settingLateRoundToHours',String(s.late_round_to_hours!==false));setValue('settingAbsenceMethod',s.absence_deduction_method||'leave_balance_then_salary');setValue('settingUnexcusedAbsenceMultiplier',s.unexcused_absence_multiplier||2);setValue('settingExitHoursPerLeaveDay',s.personal_exit_hours_per_leave_day||8);setValue('settingLeaveBalance',s.current_balance??14);setValue('settingLeaveConsumed',s.consumed_days??0);setValue('settingCycleStart',s.salary_cycle_start_day);setValue('settingCycleEnd',s.salary_cycle_end_day);setValue('settingNotes',s.notes||'');switchTab('settings')}
function salaryMonth(){return `${value('salaryYearInput')}-${value('salaryMonthSelect')}`}
async function previewSalary(){try{const employeeId=value('salaryEmployee'),m=salaryMonth();if(!employeeId||!m)throw new Error('اختر الموظف والشهر والسنة');const d=await fetchJson(`${API_BASE_URL}/salaries/preview?employee_id=${employeeId}&salary_month=${m}`);currentPreview=d;currentSalaryId=null;currentItems=d.items||[];renderPayslip(d,null);msg('salaryMessage','تمت المعاينة قبل الحفظ')}catch(e){msg('salaryMessage',e.message,true)}}
async function generateSalary(e){e.preventDefault();try{const employeeId=value('salaryEmployee'),m=salaryMonth();if(!employeeId||!m)throw new Error('اختر الموظف والشهر والسنة');const d=await fetchJson(`${API_BASE_URL}/salaries/generate`,{method:'POST',body:JSON.stringify({employee_id:employeeId,salary_month:m,status:'draft'})});currentPreview=d.draft;currentSalaryId=d.salary?.id;currentItems=d.draft?.items||[];renderPayslip(d.draft,d.salary);msg('salaryMessage',d.message||'تم توليد كشف الراتب');await loadSalaries();renderAll()}catch(err){msg('salaryMessage',err.message,true)}}
function invoiceLine(item,editable=false){return `<article class="invoice-line"><div><strong>${item.name||'-'}</strong><small>${item.reason||''}</small>${item.quantity?`<small>${money(item.quantity)} ${item.unit||''}</small>`:''}</div><div class="invoice-line-amount">${money(item.amount)}</div>${editable?`<div class="invoice-line-actions"><button class="small-btn secondary-btn" data-edit-item="${item.id}">تعديل</button><button class="small-btn danger-btn" data-delete-item="${item.id}">حذف</button></div>`:''}</article>`}
function renderPayslip(d,salary){el('payslipPreviewSection').hidden=false;const emp=d.employee||{};const status=salary?normalizeStatus(salary.status):'preview';const editable=salary&&currentSalaryId&&!['approved','paid','closed'].includes(status);el('payslipTitle').textContent=`كشف راتب - ${emp.full_name||salary?.employee_name||'-'}`;el('payslipMeta').textContent=`الشهر: ${salary?.salary_month||salaryMonth()} • الحالة: ${salary?statusLabels[status]:'معاينة'}`;setText('invoiceEmployeeName',emp.full_name||salary?.employee_name||'-');setText('invoiceSalaryMonth',salary?.salary_month||salaryMonth());setText('invoiceStatus',salary?statusLabels[status]:'معاينة');const items=d.items||[];currentItems=items;const income=items.filter(i=>i.item_type==='income'),ded=items.filter(i=>i.item_type==='deduction');el('invoiceIncomeList').innerHTML=income.length?income.map(i=>invoiceLine(i,editable)).join(''):'<div class="empty-state">لا توجد بنود دخل</div>';el('invoiceDeductionList').innerHTML=ded.length?ded.map(i=>invoiceLine(i,editable)).join(''):'<div class="empty-state">لا توجد اقتطاعات</div>';el('payslipTotalsFoot').innerHTML=`<div><span>إجمالي الدخل</span><strong>${money(d.totals?.total_income||salary?.total_income)}</strong></div><div><span>إجمالي الاقتطاعات</span><strong>${money(d.totals?.total_deductions||salary?.total_deductions)}</strong></div><div class="net"><span>صافي الراتب</span><strong>${money(d.totals?.net_salary||salary?.net_salary)}</strong></div>`;const a=d.attendance||d.snapshot?.attendance||{};el('salaryHelperSummary').innerHTML=[detail('إضافي عادي',a.normal_overtime_hours||0),detail('إضافي الجمعة',a.friday_overtime_hours||0),detail('دقائق التأخير',a.late_minutes||0),detail('غياب بعذر',a.excused_absent_days||0),detail('غياب بدون عذر',a.unexcused_absent_days||0),detail('رصيد الإجازات بعد الكشف',money(d.totals?.leave_balance_after||0)),detail('السلف المستحقة',money(d.totals?.advances_amount||0))].join('');const calc=d.calculation_details||{};el('salaryCalculationDetails').innerHTML=[detail('أجر الساعة',money(calc.hourly_rate)),detail('أجر اليوم',money(calc.daily_rate)),detail('خصم التأخير',calc.formulas?.late_deduction),detail('خصم الغياب بدون عذر',calc.formulas?.unexcused_absence),detail('رصيد الإجازات',calc.formulas?.leave_balance)].join('');el('payslipPreviewSection').scrollIntoView({behavior:'smooth',block:'start'})}
async function viewSalary(id){try{const d=await fetchJson(`${API_BASE_URL}/salaries/${id}`);const salary=d.salary;currentSalaryId=salary.id;currentItems=d.items||[];const draft={employee:{full_name:salary.employee_name,employee_number:salary.employee_number},items:d.items||[],totals:{total_income:salary.total_income,total_deductions:salary.total_deductions,net_salary:salary.net_salary,advances_amount:salary.advances,leave_balance_after:salary.snapshot?.leave_balance?.remaining_days},attendance:salary.snapshot?.attendance||{},calculation_details:salary.calculation_details||{}};renderPayslip(draft,salary);switchTab('payslips')}catch(e){msg('salaryMessage',e.message,true)}}
async function changeStatus(id,status){try{const d=await fetchJson(`${API_BASE_URL}/salaries/${id}/status`,{method:'PATCH',body:JSON.stringify({status})});msg('salaryMessage',d.message||'تم تحديث الحالة');await loadSalaries();renderAll()}catch(e){msg('salaryMessage',e.message,true)}}
async function deleteSalary(id){if(!confirm('حذف كشف الراتب؟'))return;try{const d=await fetchJson(`${API_BASE_URL}/salaries/${id}`,{method:'DELETE'});msg('salaryMessage',d.message||'تم الحذف');await loadSalaries();renderAll()}catch(e){msg('salaryMessage',e.message,true)}}
function collectItem(){return{item_type:value('itemType'),name:value('itemName'),amount:Number(value('itemAmount')||0),quantity:Number(value('itemQuantity')||0),unit:value('itemUnit')||null,reason:value('itemReason')||null,notes:value('itemNotes')||null}}
function resetItemForm(){editingItemId=null;el('salaryItemForm').reset();setText('itemSubmitBtn','إضافة الحقل إلى الكشف');msg('itemMessage','')}
async function addSalaryItem(e){e.preventDefault();try{const id=value('itemSalaryRecord')||currentSalaryId;if(!id)throw new Error('اختر كشف الراتب');const body=collectItem();const url=editingItemId?`${API_BASE_URL}/salaries/${id}/items/${editingItemId}`:`${API_BASE_URL}/salaries/${id}/items`;const method=editingItemId?'PUT':'POST';const d=await fetchJson(url,{method,body:JSON.stringify(body)});msg('itemMessage',d.message||'تم حفظ البند');resetItemForm();await loadSalaries();renderAll();await viewSalary(id)}catch(err){msg('itemMessage',err.message,true)}}
async function deleteSalaryItem(itemId){if(!currentSalaryId)return;if(!confirm('حذف هذا البند من كشف الراتب؟'))return;try{const d=await fetchJson(`${API_BASE_URL}/salaries/${currentSalaryId}/items/${itemId}`,{method:'DELETE'});msg('salaryMessage',d.message||'تم حذف البند');await loadSalaries();renderAll();await viewSalary(currentSalaryId)}catch(e){msg('salaryMessage',e.message,true)}}
function startEditItem(itemId){const item=currentItems.find(i=>String(i.id)===String(itemId));if(!item)return;editingItemId=item.id;setValue('itemSalaryRecord',currentSalaryId);setValue('itemType',item.item_type);setValue('itemName',item.name);setValue('itemAmount',item.amount);setValue('itemQuantity',item.quantity||0);setValue('itemUnit',item.unit||'');setValue('itemReason',item.reason||'');setValue('itemNotes',item.notes||'');setText('itemSubmitBtn','حفظ تعديل البند');switchTab('settings');el('salaryItemForm').scrollIntoView({behavior:'smooth',block:'start'})}
async function saveAdvance(e){e.preventDefault();try{const body={employee_id:value('advanceEmployee'),amount:Number(value('advanceAmount')||0),paid_at:value('advancePaidAt')||null,deduction_method:value('advanceDeductionMethod'),installments_count:Number(value('advanceInstallmentsCount')||1),monthly_installment_amount:Number(value('advanceMonthlyAmount')||0),deduction_start_month:value('advanceStartMonth'),reason:value('advanceReason')||null,notes:value('advanceNotes')||null};if(!body.employee_id||!body.amount||!body.deduction_start_month)throw new Error('الموظف والمبلغ وشهر بداية الخصم مطلوبة');const d=await fetchJson(`${API_BASE_URL}/salaries/advances`,{method:'POST',body:JSON.stringify(body)});msg('advanceMessage',d.message||'تم حفظ السلفة');el('advanceForm').reset();initMonths();await loadAdvances();renderAll()}catch(err){msg('advanceMessage',err.message,true)}}
function switchTab(tab){document.querySelectorAll('.finance-tab').forEach(b=>b.classList.toggle('active',b.dataset.financeTab===tab));document.querySelectorAll('.finance-section').forEach(s=>s.classList.toggle('active',s.dataset.financeSection===tab));location.hash=tab==='dashboard'?'':tab}
function openHashTab(){const h=location.hash.replace('#','');if(h)switchTab(h)}
function exportCSV(){const rows=[['id','employee','month','income','deductions','net','status'],...filteredSalaries().map(s=>[s.id,s.employee_name,s.salary_month,s.total_income,s.total_deductions,s.net_salary,statusLabels[normalizeStatus(s.status)]])];const csv=rows.map(r=>r.map(x=>`"${String(x??'').replace(/"/g,'""')}"`).join(',')).join('\n');const blob=new Blob(['\uFEFF'+csv],{type:'text/csv;charset=utf-8;'});const url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download='finance-salaries.csv';a.click();URL.revokeObjectURL(url)}
function bindEvents(){document.querySelectorAll('.finance-tab').forEach(b=>b.addEventListener('click',()=>switchTab(b.dataset.financeTab)));el('refreshFinanceBtn').addEventListener('click',loadFinanceData);el('goGenerateSalaryBtn').addEventListener('click',()=>{switchTab('payslips');el('payslipGeneratorCard').scrollIntoView({behavior:'smooth',block:'start'})});el('settingDepartment').addEventListener('change',()=>filterEmployeeSelect('settingEmployee',value('settingDepartment')));el('salaryDepartment').addEventListener('change',()=>filterEmployeeSelect('salaryEmployee',value('salaryDepartment')));el('financeSettingForm').addEventListener('submit',saveSetting);el('settingsTableBody').addEventListener('click',e=>{const b=e.target.closest('button[data-edit-setting]');if(b)editSetting(b.dataset.editSetting)});el('previewSalaryBtn').addEventListener('click',previewSalary);el('salaryGenerateForm').addEventListener('submit',generateSalary);el('recalculateSalaryBtn').addEventListener('click',()=>currentSalaryId?generateSalary(new Event('submit')):previewSalary());['salarySearchInput','salaryStatusFilter','salaryMonthFilter'].forEach(id=>el(id).addEventListener('input',renderSalariesTable));el('salariesTableBody').addEventListener('click',e=>{const b=e.target.closest('button');if(!b)return;if(b.dataset.viewSalary)viewSalary(b.dataset.viewSalary);if(b.dataset.statusId)changeStatus(b.dataset.statusId,b.dataset.status);if(b.dataset.deleteSalary)deleteSalary(b.dataset.deleteSalary)});el('approvalTableBody').addEventListener('click',e=>{const b=e.target.closest('button');if(!b)return;if(b.dataset.viewSalary)viewSalary(b.dataset.viewSalary);if(b.dataset.statusId)changeStatus(b.dataset.statusId,b.dataset.status)});el('salaryItemForm').addEventListener('submit',addSalaryItem);el('cancelItemEditBtn').addEventListener('click',resetItemForm);el('advanceForm').addEventListener('submit',saveAdvance);el('advanceAmount').addEventListener('input',calcAdvanceInstallment);el('advanceInstallmentsCount').addEventListener('input',calcAdvanceInstallment);el('advanceDeductionMethod').addEventListener('change',calcAdvanceInstallment);el('exportSalariesBtn').addEventListener('click',exportCSV);el('payslipPreviewSection').addEventListener('click',e=>{const edit=e.target.closest('button[data-edit-item]');const del=e.target.closest('button[data-delete-item]');if(edit)startEditItem(edit.dataset.editItem);if(del)deleteSalaryItem(del.dataset.deleteItem)})}
function calcAdvanceInstallment(){const amount=Number(value('advanceAmount')||0);let count=Math.max(1,Number(value('advanceInstallmentsCount')||1));if(value('advanceDeductionMethod')==='one_time'){count=1;setValue('advanceInstallmentsCount',1)}if(amount)setValue('advanceMonthlyAmount',money(amount/count))}
initFinance();
