const dayLabels={saturday:'السبت',sunday:'الأحد',monday:'الإثنين',tuesday:'الثلاثاء',wednesday:'الأربعاء',thursday:'الخميس',friday:'الجمعة'};
const shiftTypeLabels={morning:'صباحي',evening:'مسائي',friday:'جمعة',custom:'مخصص',default:'افتراضي'};
const dayKeys=Object.keys(dayLabels);
const el=(id)=>document.getElementById(id);
const value=(id)=>String(el(id)?.value||'').trim();
const setValue=(id,val)=>{const node=el(id);if(node)node.value=val??''};
const msg=(node,text,bad=false)=>{if(!node)return;node.textContent=text;node.className='inline-message '+(bad?'error-message':'success-message')};
const fmtDate=(d)=>d?String(d).split('T')[0]:'-';
const timeShort=(t)=>t?String(t).slice(0,5):'-';
const badge=(text,cls='')=>`<span class="mini-badge ${cls}">${text}</span>`;
const detail=(label,val)=>`<div class="detail-item"><span class="detail-label">${label}</span><span class="detail-value">${val||'-'}</span></div>`;
let shifts=[],assignments=[],employees=[],defaultShift=null,withoutShift=[],fridayEmployees=[],weekDistribution=[],selectedShiftDetails=null;
const shiftMessage=el('shiftMessage'),assignmentMessage=el('assignmentMessage'),shiftsTableBody=el('shiftsTableBody'),shiftDetailsEmployeesBody=el('shiftDetailsEmployeesBody'),withoutShiftBody=el('withoutShiftBody'),fridayEmployeesBody=el('fridayEmployeesBody'),weekDistributionBody=el('weekDistributionBody'),assignmentConflictBox=el('assignmentConflictBox');
async function fetchJson(url,options={}){const r=await fetch(url,{...options,headers:{Authorization:`Bearer ${token}`,'Content-Type':'application/json',...(options.headers||{})}});const d=await r.json().catch(()=>({}));if(!r.ok){const e=new Error(d.error||'فشل تنفيذ الطلب');e.data=d;throw e}return d}
function initDayPicker(){const box=el('workDaysBox');box.innerHTML=dayKeys.map(day=>`<label class="day-chip"><input type="checkbox" value="${day}" ${day!=='friday'?'checked':''}/><span>${dayLabels[day]}</span></label>`).join('')}
function getSelectedDays(){return Array.from(document.querySelectorAll('#workDaysBox input:checked')).map(i=>i.value)}
function setSelectedDays(days=[]){document.querySelectorAll('#workDaysBox input').forEach(i=>i.checked=days.includes(i.value))}
function today(){return new Date().toISOString().split('T')[0]}
function setTodayDefaults(){setValue('assignmentFrom',today());setValue('shiftEffectiveFrom',today());setValue('shiftStart','07:00');setValue('shiftEnd','15:00')}
async function initShifts(){const user=await loadLoggedUser();if(!user||(!hasAnyPermission(['shifts.view'])&&!hasAnyPermission(['shifts.manage']))){location.href='./dashboard.html';return}initDayPicker();setTodayDefaults();bindEvents();await loadEmployees();await loadShifts()}
async function loadEmployees(){try{const data=await fetchJson(`${API_BASE_URL}/employees`);employees=data.employees||[];renderDepartmentOptions()}catch(error){msg(assignmentMessage,error.message,true)}}
async function loadShifts(){try{el('shiftsCountText').textContent='جاري تحميل البيانات...';const data=await fetchJson(`${API_BASE_URL}/shifts`);shifts=data.shifts||[];assignments=data.assignments||[];defaultShift=data.default_shift||shifts.find(s=>s.is_default)||null;withoutShift=data.without_shift||[];fridayEmployees=data.friday_employees||[];weekDistribution=data.week_distribution||[];renderAll()}catch(error){el('shiftsCountText').textContent='تعذر تحميل البيانات';shiftsTableBody.innerHTML=`<tr><td colspan="10">${error.message}</td></tr>`}}
function renderAll(){renderSummary();renderDefaultShift();renderShiftOptions();renderEmployeesByDepartment();renderShiftsTable();renderWithoutShift();renderFridayEmployees();renderWeekDistribution()}
function renderSummary(){el('summaryShiftsCount').textContent=shifts.length;el('summaryAssignedCount').textContent=assignments.filter(a=>a.is_active).length;el('summaryWithoutShiftCount').textContent=withoutShift.length;el('summaryFridayCount').textContent=fridayEmployees.length}
function formatDays(days){const list=Array.isArray(days)?days:[];return list.length?list.map(d=>dayLabels[d]||d).join('، '):'-'}
function renderDefaultShift(){const box=el('defaultShiftBox');if(!defaultShift){box.innerHTML=detail('الدوام الافتراضي','غير محدد');return}box.innerHTML=[detail('الشفت',`${defaultShift.name} ${badge('افتراضي','badge-blue')}`),detail('الوقت',`${timeShort(defaultShift.start_time)} - ${timeShort(defaultShift.end_time)}`),detail('أيام العمل',formatDays(defaultShift.work_days)),detail('سماح التأخير',`${defaultShift.late_grace_minutes||0} دقيقة`)].join('')}
function renderDepartmentOptions(){const select=el('assignmentDepartment');const departments=new Map();employees.forEach(emp=>{if(emp.primary_department)departments.set(String(emp.primary_department.department_id||emp.primary_department.id),emp.primary_department.department_name);if(emp.department_id)departments.set(String(emp.department_id),emp.department_name||'بدون اسم');(emp.departments||[]).forEach(dep=>departments.set(String(dep.department_id),dep.department_name))});select.innerHTML='<option value="">اختر القسم</option>'+Array.from(departments).filter(([id,name])=>id&&name).map(([id,name])=>`<option value="${id}">${name}</option>`).join('')}
function renderEmployeesByDepartment(){const select=el('assignmentEmployees');const departmentId=value('assignmentDepartment');const filtered=departmentId?employees.filter(emp=>String(emp.department_id)===departmentId||(emp.departments||[]).some(dep=>String(dep.department_id)===departmentId)):[];if(!departmentId){select.innerHTML='<option value="">اختر القسم أولًا</option>';return}if(!filtered.length){select.innerHTML='<option value="">لا يوجد موظفون في هذا القسم</option>';return}const active=assignments.filter(a=>a.is_active);select.innerHTML=filtered.map(emp=>{const linked=active.find(a=>String(a.employee_id)===String(emp.id));const warn=linked?` — مرتبط حاليًا بـ ${linked.shift_name}`:'';return `<option value="${emp.id}" data-linked="${linked?'true':'false'}">${emp.full_name} - ${emp.employee_number||emp.id}${warn}</option>`}).join('');showSelectedEmployeeWarnings()}
function showSelectedEmployeeWarnings(){const selected=Array.from(el('assignmentEmployees').selectedOptions||[]);const warnings=selected.filter(o=>o.dataset.linked==='true').map(o=>o.textContent);if(!warnings.length){assignmentConflictBox.hidden=true;assignmentConflictBox.textContent='';return}assignmentConflictBox.hidden=false;assignmentConflictBox.innerHTML='الموظفون التاليون مرتبطون بشفت آخر:<br>'+warnings.map(w=>`• ${w}`).join('<br>')}
function renderShiftOptions(){const select=el('assignmentShift');select.innerHTML='<option value="">اختر الشفت</option>'+shifts.filter(s=>s.is_active).map(s=>`<option value="${s.id}">${s.name} - ${shiftTypeLabels[s.shift_type]||s.shift_type} (${timeShort(s.start_time)} - ${timeShort(s.end_time)})</option>`).join('')}
function filteredShifts(){const q=value('shiftSearchInput').toLowerCase(),type=value('shiftTypeFilter'),status=value('shiftStatusFilter');return shifts.filter(s=>{const text=[s.name,s.department_names,s.shift_type].join(' ').toLowerCase();const statusOk=!status||(status==='active'?s.is_active:!s.is_active);return(!q||text.includes(q))&&(!type||s.shift_type===type)&&statusOk})}
function renderShiftsTable(){const list=filteredShifts();el('shiftsCountText').textContent=`عرض ${list.length} من أصل ${shifts.length} شفت`;if(!list.length){shiftsTableBody.innerHTML='<tr><td colspan="10">لا توجد شفتات مطابقة</td></tr>';return}shiftsTableBody.innerHTML=list.map(s=>`<tr><td>${s.name} ${s.is_default?badge('افتراضي','badge-blue'):''}</td><td>${shiftTypeLabels[s.shift_type]||s.shift_type||'-'}</td><td>${timeShort(s.start_time)} - ${timeShort(s.end_time)}</td><td>${formatDays(s.work_days)}</td><td>${fmtDate(s.effective_from)}</td><td>${fmtDate(s.effective_to)}</td><td>${s.department_names||'-'}</td><td>${s.employee_count||0}</td><td>${badge(s.is_active?'نشط':'مؤرشف',s.is_active?'status-active':'status-inactive')}</td><td><div class="row-actions"><button class="small-btn secondary-btn" data-action="details" data-id="${s.id}">عرض التفاصيل</button><button class="small-btn edit-btn" data-action="edit" data-id="${s.id}">تعديل</button><button class="small-btn secondary-btn" data-action="archive" data-id="${s.id}" ${s.is_default?'disabled':''}>أرشفة</button><button class="small-btn danger-btn" data-action="delete" data-id="${s.id}" ${s.is_default?'disabled':''}>حذف</button></div></td></tr>`).join('')}
function renderWithoutShift(){if(!withoutShift.length){withoutShiftBody.innerHTML='<tr><td colspan="5">لا يوجد موظفون بدون شفت مخصص</td></tr>';return}withoutShiftBody.innerHTML=withoutShift.map(emp=>`<tr><td>${emp.full_name}</td><td>${emp.employee_number||emp.id}</td><td>${emp.department_name||'-'}</td><td>${emp.job_title||'-'}</td><td><button class="small-btn secondary-btn" data-quick-assign="${emp.id}" data-department="${emp.department_id||''}">ربط بشفت</button></td></tr>`).join('')}
function renderFridayEmployees(){if(!fridayEmployees.length){fridayEmployeesBody.innerHTML='<tr><td colspan="5">لا يوجد موظفون مرتبطون بدوام الجمعة</td></tr>';return}fridayEmployeesBody.innerHTML=fridayEmployees.map(emp=>`<tr><td>${emp.full_name}</td><td>${emp.employee_number||emp.id}</td><td>${emp.department_name||'-'}</td><td>${emp.shift_name||'-'}</td><td>${fmtDate(emp.effective_from)} - ${fmtDate(emp.effective_to)}</td></tr>`).join('')}
function renderWeekDistribution(){if(!weekDistribution.length){weekDistributionBody.innerHTML='<tr><td colspan="9">لا توجد بيانات توزيع أسبوعي</td></tr>';return}weekDistributionBody.innerHTML=weekDistribution.map(row=>`<tr><td>${row.full_name} ${row.is_default_shift_applied?badge('افتراضي','badge-blue'):''}</td><td>${row.department_name||'-'}</td>${dayKeys.map(day=>`<td>${row.schedule?.[day]||'-'}</td>`).join('')}</tr>`).join('')}
function collectShiftPayload(){return{name:value('shiftName'),shift_type:value('shiftType'),start_time:value('shiftStart'),end_time:value('shiftEnd'),official_work_hours:Number(value('officialWorkHours')||8),effective_from:value('shiftEffectiveFrom')||null,effective_to:value('shiftEffectiveTo')||null,late_grace_minutes:Number(value('lateGraceMinutes')||0),absent_after_minutes:Number(value('absentAfterMinutes')||180),repeats_weekly:value('repeatsWeekly')==='true',is_default:value('isDefaultShift')==='true'||value('shiftType')==='default',is_active:value('shiftActive')==='true',work_days:getSelectedDays(),notes:value('shiftNotes')||null}}
function resetShiftForm(){el('shiftForm').reset();setValue('shiftId','');el('shiftFormTitle').textContent='إضافة شفت';setTodayDefaults();setValue('shiftType','morning');setValue('shiftActive','true');setValue('officialWorkHours','8');setValue('lateGraceMinutes','0');setValue('absentAfterMinutes','180');setValue('repeatsWeekly','true');setValue('isDefaultShift','false');setSelectedDays(['saturday','sunday','monday','tuesday','wednesday','thursday']);el('timeImpactWarning').hidden=true}
function editShift(id){const s=shifts.find(item=>String(item.id)===String(id));if(!s)return;setValue('shiftId',s.id);el('shiftFormTitle').textContent=s.is_default?'تعديل الدوام الافتراضي':'تعديل شفت';setValue('shiftName',s.name);setValue('shiftType',s.shift_type||'custom');setValue('shiftActive',String(Boolean(s.is_active)));setValue('shiftStart',timeShort(s.start_time));setValue('shiftEnd',timeShort(s.end_time));setValue('officialWorkHours',s.official_work_hours||8);setValue('shiftEffectiveFrom',fmtDate(s.effective_from)==='-'?'':fmtDate(s.effective_from));setValue('shiftEffectiveTo',fmtDate(s.effective_to)==='-'?'':fmtDate(s.effective_to));setValue('lateGraceMinutes',s.late_grace_minutes||0);setValue('absentAfterMinutes',s.absent_after_minutes||180);setValue('repeatsWeekly',String(Boolean(s.repeats_weekly)));setValue('isDefaultShift',String(Boolean(s.is_default)));setValue('shiftNotes',s.notes||'');setSelectedDays(Array.isArray(s.work_days)?s.work_days:[]);el('timeImpactWarning').hidden=false;el('shiftFormCard').scrollIntoView({behavior:'smooth',block:'start'})}
async function saveShift(event){event.preventDefault();const payload=collectShiftPayload();if(!payload.name||!payload.start_time||!payload.end_time){msg(shiftMessage,'اسم الشفت ووقت البداية والنهاية مطلوبة',true);return}if(!payload.work_days.length){msg(shiftMessage,'يجب اختيار يوم عمل واحد على الأقل',true);return}const id=value('shiftId');try{const data=await fetchJson(id?`${API_BASE_URL}/shifts/${id}`:`${API_BASE_URL}/shifts`,{method:id?'PUT':'POST',body:JSON.stringify(payload)});msg(shiftMessage,data.message||'تم حفظ الشفت');resetShiftForm();await loadShifts()}catch(error){msg(shiftMessage,error.message,true)}}
async function assignShift(event){event.preventDefault();const employeeIds=Array.from(el('assignmentEmployees').selectedOptions).map(o=>Number(o.value)).filter(Boolean);const payload={employee_ids:employeeIds,shift_id:value('assignmentShift'),effective_from:value('assignmentFrom')||null,effective_to:value('assignmentTo')||null,transfer_existing:value('transferExisting')==='true'};if(!payload.employee_ids.length||!payload.shift_id){msg(assignmentMessage,'يجب اختيار موظف واحد على الأقل والشفت',true);return}try{const data=await fetchJson(`${API_BASE_URL}/shifts/assign`,{method:'POST',body:JSON.stringify(payload)});msg(assignmentMessage,data.message||'تم ربط الموظفين بالشفت');el('assignmentForm').reset();setTodayDefaults();renderEmployeesByDepartment();await loadShifts()}catch(error){if(error.data?.code==='SHIFT_ASSIGNMENT_CONFLICT'&&Array.isArray(error.data.conflicts)){assignmentConflictBox.hidden=false;assignmentConflictBox.innerHTML='يوجد تعارضات:<br>'+error.data.conflicts.map(c=>`• ${c.employee_name} مرتبط بـ ${c.shift_name} من ${fmtDate(c.effective_from)} إلى ${fmtDate(c.effective_to)}`).join('<br>')}msg(assignmentMessage,error.message,true)}}
async function showShiftDetails(id){try{const data=await fetchJson(`${API_BASE_URL}/shifts/${id}`);selectedShiftDetails=data;const s=data.shift;el('shiftDetailsSection').hidden=false;el('detailsShiftTitle').textContent=s.name;el('detailsShiftMeta').textContent=`${shiftTypeLabels[s.shift_type]||s.shift_type} • ${timeShort(s.start_time)} - ${timeShort(s.end_time)} • ${formatDays(s.work_days)}`;const rows=data.assignments||[];shiftDetailsEmployeesBody.innerHTML=rows.length?rows.map(a=>`<tr><td>${a.employee_name}</td><td>${a.employee_number||'-'}</td><td>${a.department_name||'-'}</td><td>${a.job_title||'-'}</td><td>${fmtDate(a.effective_from)}</td><td>${fmtDate(a.effective_to)}</td><td>${badge(a.is_active?'نشط':'منتهي',a.is_active?'status-active':'status-inactive')}</td><td><div class="row-actions"><button class="small-btn danger-btn" data-remove-assignment="${a.id}">إزالة</button><button class="small-btn secondary-btn" data-move-assignment="${a.id}">نقل</button></div></td></tr>`).join(''):'<tr><td colspan="8">لا يوجد موظفون مرتبطون بهذا الشفت</td></tr>';el('shiftDetailsSection').scrollIntoView({behavior:'smooth',block:'start'})}catch(error){msg(shiftMessage,error.message,true)}}
async function archiveShift(id){if(!confirm('هل تريد أرشفة هذا الشفت؟'))return;try{const data=await fetchJson(`${API_BASE_URL}/shifts/${id}/archive`,{method:'PATCH',body:JSON.stringify({})});msg(shiftMessage,data.message||'تمت الأرشفة');await loadShifts()}catch(error){msg(shiftMessage,error.message,true)}}
async function deleteShift(id){if(!confirm('حذف الشفت نهائيًا؟ إذا كان مرتبطًا بموظفين سيمنع النظام الحذف.'))return;try{const data=await fetchJson(`${API_BASE_URL}/shifts/${id}`,{method:'DELETE'});msg(shiftMessage,data.message||'تم الحذف');await loadShifts()}catch(error){msg(shiftMessage,error.message,true)}}
async function removeAssignment(id){if(!confirm('إزالة الموظف من هذا الشفت؟'))return;try{const data=await fetchJson(`${API_BASE_URL}/shifts/assignments/${id}/remove`,{method:'PATCH',body:JSON.stringify({reason:'إزالة من صفحة الشفتات'})});msg(shiftMessage,data.message||'تمت الإزالة');await loadShifts();if(selectedShiftDetails?.shift?.id)await showShiftDetails(selectedShiftDetails.shift.id)}catch(error){msg(shiftMessage,error.message,true)}}
async function moveAssignment(id){const active=shifts.filter(s=>s.is_active&&!s.is_default);const options=active.map(s=>`${s.id}: ${s.name}`).join('\n');const target=prompt(`اكتب رقم الشفت الجديد:\n${options}`);if(!target)return;const newShiftId=Number(String(target).split(':')[0].trim());if(!newShiftId){msg(shiftMessage,'رقم الشفت غير صحيح',true);return}try{const data=await fetchJson(`${API_BASE_URL}/shifts/assignments/${id}/move`,{method:'PATCH',body:JSON.stringify({new_shift_id:newShiftId,effective_from:today()})});msg(shiftMessage,data.message||'تم النقل');await loadShifts();if(selectedShiftDetails?.shift?.id)await showShiftDetails(selectedShiftDetails.shift.id)}catch(error){msg(shiftMessage,error.message,true)}}
function quickAssign(employeeId,departmentId){setValue('assignmentDepartment',departmentId||'');renderEmployeesByDepartment();Array.from(el('assignmentEmployees').options).forEach(o=>o.selected=String(o.value)===String(employeeId));el('assignmentForm').scrollIntoView({behavior:'smooth',block:'start'})}
function bindEvents(){el('shiftForm').addEventListener('submit',saveShift);el('assignmentForm').addEventListener('submit',assignShift);el('cancelShiftEditBtn').addEventListener('click',resetShiftForm);el('refreshShiftsBtn').addEventListener('click',async()=>{await loadEmployees();await loadShifts()});el('openShiftFormBtn').addEventListener('click',()=>el('shiftFormCard').scrollIntoView({behavior:'smooth',block:'start'}));el('editDefaultShiftBtn').addEventListener('click',()=>{if(defaultShift)editShift(defaultShift.id)});el('assignmentDepartment').addEventListener('change',renderEmployeesByDepartment);el('assignmentEmployees').addEventListener('change',showSelectedEmployeeWarnings);['shiftSearchInput','shiftTypeFilter','shiftStatusFilter'].forEach(id=>el(id).addEventListener('input',renderShiftsTable));el('shiftType').addEventListener('change',()=>{if(value('shiftType')==='friday')setSelectedDays(['friday']);if(value('shiftType')==='default')setValue('isDefaultShift','true')});shiftsTableBody.addEventListener('click',e=>{const b=e.target.closest('button');if(!b)return;const id=b.dataset.id,a=b.dataset.action;if(a==='details')showShiftDetails(id);if(a==='edit')editShift(id);if(a==='archive')archiveShift(id);if(a==='delete')deleteShift(id)});el('closeShiftDetailsBtn').addEventListener('click',()=>{el('shiftDetailsSection').hidden=true;selectedShiftDetails=null});shiftDetailsEmployeesBody.addEventListener('click',e=>{const b=e.target.closest('button');if(!b)return;if(b.dataset.removeAssignment)removeAssignment(b.dataset.removeAssignment);if(b.dataset.moveAssignment)moveAssignment(b.dataset.moveAssignment)});withoutShiftBody.addEventListener('click',e=>{const b=e.target.closest('button[data-quick-assign]');if(b)quickAssign(b.dataset.quickAssign,b.dataset.department)})}
initShifts();
