const shiftsTableBody=document.getElementById('shiftsTableBody');
const assignmentsTableBody=document.getElementById('assignmentsTableBody');
const shiftForm=document.getElementById('shiftForm');
const assignmentForm=document.getElementById('assignmentForm');
const shiftMessage=document.getElementById('shiftMessage');
const assignmentMessage=document.getElementById('assignmentMessage');
const employeeSelect=document.getElementById('assignmentEmployee');
const shiftSelect=document.getElementById('assignmentShift');
const countText=document.getElementById('shiftsCountText');
let shifts=[];let assignments=[];let employees=[];
function msg(el,t,b=false){el.textContent=t;el.className='inline-message '+(b?'error-message':'success-message')}
function v(id){return(document.getElementById(id)?.value||'').trim()}
function sv(id,x){let e=document.getElementById(id);if(e)e.value=x??''}
function fmt(d){return d?String(d).split('T')[0]:'-'}
async function initShifts(){let u=await loadLoggedUser();if(!u||u.role==='employee'){location.href='./dashboard.html';return}document.getElementById('assignmentFrom').value=new Date().toISOString().split('T')[0];await loadEmployees();await loadShifts()}
async function fetchJson(url,options={}){let r=await fetch(url,{headers:{Authorization:`Bearer ${token}`,'Content-Type':'application/json'},...options});let d=await r.json().catch(()=>({}));if(!r.ok)throw new Error(d.error||'فشل الطلب');return d}
async function loadEmployees(){try{let d=await fetchJson(`${API_BASE_URL}/employees`);employees=d.employees||[];employeeSelect.innerHTML='<option value="">اختر الموظف</option>';employees.forEach(e=>employeeSelect.innerHTML+=`<option value="${e.id}">${e.full_name} - ${e.primary_department?.department_name||e.department_name||'بدون قسم'}</option>`)}catch(e){employeeSelect.innerHTML='<option value="">تعذر تحميل الموظفين</option>';msg(assignmentMessage,e.message,true)}}
async function loadShifts(){try{countText.textContent='جاري تحميل البيانات...';let d=await fetchJson(`${API_BASE_URL}/shifts`);shifts=d.shifts||[];assignments=d.assignments||[];renderShifts();renderAssignments();renderShiftOptions()}catch(e){countText.textContent='تعذر تحميل الشفتات';shiftsTableBody.innerHTML=`<tr><td colspan="8">${e.message}</td></tr>`}}
function renderShiftOptions(){shiftSelect.innerHTML='<option value="">اختر الشفت</option>';shifts.filter(s=>s.is_active).forEach(s=>shiftSelect.innerHTML+=`<option value="${s.id}">${s.name} (${String(s.start_time).slice(0,5)} - ${String(s.end_time).slice(0,5)})</option>`)}
function renderShifts(){countText.textContent=`عدد الشفتات: ${shifts.length}`;if(!shifts.length){shiftsTableBody.innerHTML='<tr><td colspan="8">لا توجد شفتات</td></tr>';return}shiftsTableBody.innerHTML='';shifts.forEach(s=>{let tr=document.createElement('tr');tr.innerHTML=`<td>${s.id}</td><td>${s.name}</td><td>${String(s.start_time).slice(0,5)}</td><td>${String(s.end_time).slice(0,5)}</td><td>${s.late_grace_minutes||0} دقيقة</td><td>${s.absent_after_minutes||180} دقيقة</td><td><span class="status-badge ${s.is_active?'active-badge':'inactive-badge'}">${s.is_active?'نشط':'معطل'}</span></td><td><div class="row-actions"><button class="edit-btn small-btn" data-a="edit" data-id="${s.id}">تعديل</button><button class="danger-btn small-btn" data-a="delete" data-id="${s.id}">حذف</button></div></td>`;shiftsTableBody.appendChild(tr)})}
function renderAssignments(){if(!assignments.length){assignmentsTableBody.innerHTML='<tr><td colspan="6">لا توجد ارتباطات شفتات</td></tr>';return}assignmentsTableBody.innerHTML='';assignments.forEach(a=>{assignmentsTableBody.innerHTML+=`<tr><td>${a.id}</td><td>${a.employee_name}</td><td>${a.shift_name}</td><td>${fmt(a.effective_from)}</td><td>${fmt(a.effective_to)}</td><td><span class="status-badge ${a.is_active?'active-badge':'inactive-badge'}">${a.is_active?'نشط':'منتهي'}</span></td></tr>`})}
function editShift(id){let s=shifts.find(x=>String(x.id)===String(id));if(!s)return;sv('shiftId',s.id);sv('shiftName',s.name);sv('shiftStart',String(s.start_time).slice(0,5));sv('shiftEnd',String(s.end_time).slice(0,5));sv('lateGraceMinutes',s.late_grace_minutes||0);sv('absentAfterMinutes',s.absent_after_minutes||180);sv('shiftActive',String(s.is_active));document.getElementById('shiftFormTitle').textContent='تعديل شفت';scrollTo({top:0,behavior:'smooth'})}
function resetShiftForm(){shiftForm.reset();sv('shiftId','');sv('shiftStart','07:00');sv('shiftEnd','15:00');sv('lateGraceMinutes','0');sv('absentAfterMinutes','180');sv('shiftActive','true');document.getElementById('shiftFormTitle').textContent='إضافة شفت'}
shiftForm.addEventListener('submit',async e=>{e.preventDefault();let body={name:v('shiftName'),start_time:v('shiftStart'),end_time:v('shiftEnd'),late_grace_minutes:Number(v('lateGraceMinutes')||0),absent_after_minutes:Number(v('absentAfterMinutes')||180),is_active:v('shiftActive')==='true'};if(!body.name||!body.start_time||!body.end_time){msg(shiftMessage,'اسم الشفت ووقت البداية والنهاية مطلوبة',true);return}let id=v('shiftId');try{let d=await fetchJson(id?`${API_BASE_URL}/shifts/${id}`:`${API_BASE_URL}/shifts`,{method:id?'PUT':'POST',body:JSON.stringify(body)});msg(shiftMessage,d.message||'تم حفظ الشفت');resetShiftForm();await loadShifts()}catch(error){msg(shiftMessage,error.message,true)}});
assignmentForm.addEventListener('submit',async e=>{e.preventDefault();let body={employee_id:v('assignmentEmployee'),shift_id:v('assignmentShift'),effective_from:v('assignmentFrom')||null,effective_to:v('assignmentTo')||null};if(!body.employee_id||!body.shift_id){msg(assignmentMessage,'الموظف والشفت مطلوبان',true);return}try{let d=await fetchJson(`${API_BASE_URL}/shifts/assign`,{method:'POST',body:JSON.stringify(body)});msg(assignmentMessage,d.message||'تم ربط الشفت');assignmentForm.reset();document.getElementById('assignmentFrom').value=new Date().toISOString().split('T')[0];await loadShifts()}catch(error){msg(assignmentMessage,error.message,true)}});
async function deleteShift(id){if(!confirm('هل أنت متأكد من حذف الشفت؟'))return;try{let d=await fetchJson(`${API_BASE_URL}/shifts/${id}`,{method:'DELETE'});msg(shiftMessage,d.message||'تم حذف الشفت');await loadShifts()}catch(error){msg(shiftMessage,error.message,true)}}
shiftsTableBody.addEventListener('click',e=>{let b=e.target.closest('button');if(!b)return;if(b.dataset.a==='edit')editShift(b.dataset.id);if(b.dataset.a==='delete')deleteShift(b.dataset.id)});
document.getElementById('cancelShiftEditBtn').addEventListener('click',resetShiftForm);document.getElementById('refreshShiftsBtn').addEventListener('click',async()=>{await loadEmployees();await loadShifts()});
initShifts();
