const employeeListEl=document.getElementById('employeesPermissionList');
const jobTitlesListEl=document.getElementById('jobTitlesList');
const logsListEl=document.getElementById('permissionLogsList');
const employeeSearch=document.getElementById('employeeSearch');
const employeePermissionForm=document.getElementById('employeePermissionForm');
const employeeMessage=document.getElementById('employeePermissionMessage');
const jobTitleForm=document.getElementById('jobTitleForm');
const jobTitleMessage=document.getElementById('jobTitleMessage');
const jobTitlePermissionsBox=document.getElementById('jobTitlePermissionsBox');
let employees=[];let jobTitles=[];let permissionDefinitions=[];let permissionGroups={};let selectedEmployeeId=null;let selectedJobTitleId=null;let selectedEmployeeSummary=null;
const roleLabels={admin:'مدير النظام',hr:'الموارد البشرية',employee:'موظف',manager:'مدير قسم',finance:'المالية'};
function msg(el,t,b=false){el.textContent=t;el.className='inline-message '+(b?'error-message':'success-message')}
function normalize(v){if(!v)return[];if(Array.isArray(v))return v.flatMap(normalize);return String(v).split(',').map(x=>x.trim()).filter(Boolean)}
function unique(items){return Array.from(new Set(normalize(items)))}
function labelOfPermission(key){return permissionDefinitions.find(p=>p.key===key)?.label||key}
function moduleOfPermission(key){return permissionDefinitions.find(p=>p.key===key)?.module||'أخرى'}
async function fetchJson(url,opt={}){let r=await fetch(url,{headers:{Authorization:`Bearer ${token}`,'Content-Type':'application/json'},...opt});let d=await r.json().catch(()=>({}));if(!r.ok)throw new Error(d.error||'فشل الطلب');return d}
async function initUsers(){const user=await loadLoggedUser();if(!user)return;if(user.role!=='admin'&&!normalize(user.roles).includes('admin')&&!hasAnyPermission(['permissions.view','permissions.manage'])){location.href='./dashboard.html';return}bindTabs();await loadBaseData();await Promise.all([loadEmployees(),loadJobTitles(),loadLogs()]);renderPermissionControls()}
function bindTabs(){document.querySelectorAll('.permissions-tab').forEach(btn=>btn.addEventListener('click',()=>{document.querySelectorAll('.permissions-tab').forEach(b=>b.classList.remove('active'));document.querySelectorAll('.permissions-panel').forEach(p=>p.classList.remove('active'));btn.classList.add('active');document.getElementById(btn.dataset.tab).classList.add('active')}))}
async function loadBaseData(){let d=await fetchJson(`${API_BASE_URL}/permissions/permissions`);permissionDefinitions=d.permissions||[];permissionGroups=d.groups||groupPermissions(permissionDefinitions)}
function groupPermissions(list){return list.reduce((m,p)=>{if(!m[p.module])m[p.module]=[];m[p.module].push(p);return m},{})}
async function loadEmployees(){try{let d=await fetchJson(`${API_BASE_URL}/employees`);employees=d.employees||[];renderEmployees()}catch(e){employeeListEl.innerHTML=`<div class="empty-soft">${e.message}</div>`}}
async function loadJobTitles(){try{let d=await fetchJson(`${API_BASE_URL}/permissions/job-titles`);jobTitles=d.job_titles||[];if(d.permissions){permissionDefinitions=d.permissions;permissionGroups=d.groups||groupPermissions(permissionDefinitions)}renderJobTitles();renderJobTitlePermissions()}catch(e){jobTitlesListEl.innerHTML=`<div class="empty-soft">${e.message}</div>`}}
async function loadLogs(){try{let d=await fetchJson(`${API_BASE_URL}/permissions/logs`);renderLogs(d.logs||[])}catch(e){logsListEl.innerHTML=`<div class="empty-soft">${e.message}</div>`}}
function renderEmployees(){let q=(employeeSearch.value||'').trim().toLowerCase();let list=employees.filter(e=>[e.full_name,e.employee_number,e.job_title,e.job_title_name,e.department_name].filter(Boolean).join(' ').toLowerCase().includes(q));if(!list.length){employeeListEl.innerHTML='<div class="empty-soft">لا يوجد موظفون مطابقون</div>';return}employeeListEl.innerHTML=list.map(e=>`<button type="button" class="side-list-item ${String(e.id)===String(selectedEmployeeId)?'active':''}" data-id="${e.id}"><strong>${e.full_name}</strong><small>${e.employee_number||'-'} · ${e.job_title||'بدون مسمى'}</small></button>`).join('')}
function renderJobTitles(){if(!jobTitles.length){jobTitlesListEl.innerHTML='<div class="empty-soft">لا توجد مسميات وظيفية</div>';return}jobTitlesListEl.innerHTML=jobTitles.map(j=>`<button type="button" class="side-list-item ${String(j.id)===String(selectedJobTitleId)?'active':''}" data-id="${j.id}"><strong>${j.name}</strong><small>${j.status==='active'?'نشط':j.status==='inactive'?'غير نشط':'مؤرشف'} · ${j.employees_count||0} موظف</small></button>`).join('')}
function renderPermissionControls(){let roleSelect=document.getElementById('employeeRolesSelect');roleSelect.innerHTML=Object.entries(roleLabels).map(([k,l])=>`<option value="${k}">${l}</option>`).join('');let options=permissionDefinitions.map(p=>`<option value="${p.key}">${p.label}</option>`).join('');document.getElementById('employeeDirectPermissionsSelect').innerHTML=options;document.getElementById('employeeDeniedPermissionsSelect').innerHTML=options;renderJobTitlePermissions()}
function renderJobTitlePermissions(selected=[]){if(!permissionDefinitions.length)return;let selectedSet=new Set(normalize(selected));jobTitlePermissionsBox.innerHTML=Object.entries(permissionGroups).map(([module,perms])=>`<section class="permission-group"><h4>${module}</h4><div class="permission-checks">${perms.map(p=>`<label class="permission-check"><input type="checkbox" name="jobTitlePermission" value="${p.key}" ${selectedSet.has(p.key)?'checked':''}><span>${p.label}<small>${p.key}</small></span></label>`).join('')}</div></section>`).join('')}
function chips(title,items,cls,empty='لا توجد'){let arr=unique(items);return `<section class="permission-source-card"><h3>${title}</h3><div class="permission-chip-list">${arr.length?arr.map(p=>`<span class="permission-chip ${cls}" title="${p}">${labelOfPermission(p)}</span>`).join(''):`<span class="permission-chip">${empty}</span>`}</div></section>`}
function selectValues(id,values){let set=new Set(normalize(values));document.querySelectorAll(`#${id} option`).forEach(o=>o.selected=set.has(o.value))}
async function selectEmployee(id){selectedEmployeeId=id;renderEmployees();document.getElementById('selectedEmployeeTitle').textContent='جاري تحميل الصلاحيات...';document.getElementById('employeePermissionSummary').innerHTML='<div class="empty-soft">جاري تحميل الصلاحيات...</div>';employeePermissionForm.style.display='none';try{let d=await fetchJson(`${API_BASE_URL}/permissions/employees/${id}`);selectedEmployeeSummary=d.summary;renderEmployeeSummary(d.summary)}catch(e){document.getElementById('employeePermissionSummary').innerHTML=`<div class="empty-soft">${e.message}</div>`}}
function renderEmployeeSummary(s){let emp=employees.find(e=>String(e.id)===String(s.employee_id));document.getElementById('selectedEmployeeTitle').textContent=emp?`${emp.full_name} - ${emp.employee_number||''}`:'صلاحيات الموظف';document.getElementById('selectedEmployeeHelp').textContent=`المسمى الوظيفي الحالي: ${s.job_title?.name||emp?.job_title||'غير محدد'}`;document.getElementById('employeePermissionSummary').innerHTML=chips('صلاحيات المسمى الوظيفي',s.job_title_permissions,'inherited')+chips('صلاحيات الأدوار',s.role_permissions,'inherited')+chips('صلاحيات إضافية',s.direct_permissions,'extra')+chips('صلاحيات مستثناة',s.denied_permissions,'denied')+chips('الصلاحيات الفعلية',s.effective_permissions,'effective');employeePermissionForm.style.display='grid';selectValues('employeeRolesSelect',s.roles);selectValues('employeeDirectPermissionsSelect',s.direct_permissions);selectValues('employeeDeniedPermissionsSelect',s.denied_permissions)}
function valuesOfSelect(id){return Array.from(document.getElementById(id).selectedOptions).map(o=>o.value)}
employeePermissionForm.addEventListener('submit',async e=>{e.preventDefault();if(!selectedEmployeeId)return msg(employeeMessage,'اختر موظفًا أولاً',true);let body={roles:valuesOfSelect('employeeRolesSelect'),direct_permissions:valuesOfSelect('employeeDirectPermissionsSelect'),denied_permissions:valuesOfSelect('employeeDeniedPermissionsSelect')};try{let d=await fetchJson(`${API_BASE_URL}/permissions/employees/${selectedEmployeeId}`,{method:'PUT',body:JSON.stringify(body)});msg(employeeMessage,d.message||'تم حفظ صلاحيات الموظف');selectedEmployeeSummary=d.summary;renderEmployeeSummary(d.summary);await loadLogs()}catch(err){msg(employeeMessage,err.message,true)}});
function selectJobTitle(id){let j=jobTitles.find(x=>String(x.id)===String(id));if(!j)return;selectedJobTitleId=j.id;renderJobTitles();document.getElementById('jobTitleFormTitle').textContent='تعديل مسمى وظيفي';document.getElementById('jobTitleId').value=j.id;document.getElementById('jobTitleName').value=j.name||'';document.getElementById('jobTitleCode').value=j.code||'';document.getElementById('jobTitleStatus').value=j.status||'active';document.getElementById('jobTitleDescription').value=j.description||'';renderJobTitlePermissions(j.default_permissions||[])}
function resetJobTitleForm(){selectedJobTitleId=null;document.getElementById('jobTitleFormTitle').textContent='إنشاء مسمى وظيفي';jobTitleForm.reset();document.getElementById('jobTitleId').value='';document.getElementById('jobTitleStatus').value='active';renderJobTitlePermissions([]);renderJobTitles()}
jobTitleForm.addEventListener('submit',async e=>{e.preventDefault();let id=document.getElementById('jobTitleId').value;let body={name:document.getElementById('jobTitleName').value.trim(),code:document.getElementById('jobTitleCode').value.trim(),status:document.getElementById('jobTitleStatus').value,description:document.getElementById('jobTitleDescription').value.trim(),default_permissions:Array.from(document.querySelectorAll('[name="jobTitlePermission"]:checked')).map(c=>c.value)};try{let d=await fetchJson(id?`${API_BASE_URL}/permissions/job-titles/${id}`:`${API_BASE_URL}/permissions/job-titles`,{method:id?'PUT':'POST',body:JSON.stringify(body)});msg(jobTitleMessage,d.message||'تم الحفظ');await loadJobTitles();selectJobTitle(d.job_title.id);await loadLogs()}catch(err){msg(jobTitleMessage,err.message,true)}});
document.getElementById('disableJobTitleBtn').addEventListener('click',async()=>{let id=document.getElementById('jobTitleId').value;if(!id)return msg(jobTitleMessage,'اختر مسمى وظيفيًا أولاً',true);if(!confirm('هل تريد تعطيل هذا المسمى الوظيفي؟'))return;try{let d=await fetchJson(`${API_BASE_URL}/permissions/job-titles/${id}/disable`,{method:'PATCH'});msg(jobTitleMessage,d.message||'تم التعطيل');await loadJobTitles();selectJobTitle(id);await loadLogs()}catch(e){msg(jobTitleMessage,e.message,true)}});
document.getElementById('deleteJobTitleBtn').addEventListener('click',async()=>{let id=document.getElementById('jobTitleId').value;if(!id)return msg(jobTitleMessage,'اختر مسمى وظيفيًا أولاً',true);if(!confirm('هل تريد حذف أو أرشفة هذا المسمى؟'))return;try{let d=await fetchJson(`${API_BASE_URL}/permissions/job-titles/${id}`,{method:'DELETE'});msg(jobTitleMessage,d.message||'تم التنفيذ');resetJobTitleForm();await loadJobTitles();await loadLogs()}catch(e){msg(jobTitleMessage,e.message,true)}});
function renderLogs(logs){if(!logs.length){logsListEl.innerHTML='<div class="empty-soft">لا توجد تعديلات مسجلة</div>';return}logsListEl.innerHTML=logs.map(l=>`<article class="permission-log-item"><strong>${l.change_type}</strong><small>${l.actor_name||'-'} · ${String(l.created_at||'').replace('T',' ').slice(0,16)}</small></article>`).join('')}
employeeListEl.addEventListener('click',e=>{let b=e.target.closest('.side-list-item');if(b)selectEmployee(b.dataset.id)});
jobTitlesListEl.addEventListener('click',e=>{let b=e.target.closest('.side-list-item');if(b)selectJobTitle(b.dataset.id)});
employeeSearch.addEventListener('input',renderEmployees);document.getElementById('clearEmployeeSelectionBtn').addEventListener('click',()=>{selectedEmployeeId=null;employeePermissionForm.style.display='none';document.getElementById('selectedEmployeeTitle').textContent='اختر موظفًا';document.getElementById('employeePermissionSummary').innerHTML='';renderEmployees()});
document.getElementById('newJobTitleBtn').addEventListener('click',resetJobTitleForm);document.getElementById('resetJobTitleBtn').addEventListener('click',resetJobTitleForm);document.getElementById('refreshLogsBtn').addEventListener('click',loadLogs);
initUsers();
